import { OrganisationDto } from "../models/organizationDto";

export const org_data: OrganisationDto[] = [
    {
        "sdlNo": "SDL1234567890",
        "setaId": 101,
        "seta": "BankSETA",
        "sicCode": "6411",
        "organisationRegistrationNumber": "1995/012345/07",
        "organisationName": "FinTrust Bank Ltd",
        "organisationTradingName": "FinTrust",
        "organisationFaxNumber": "+27-11-123-4567",
        "organisationContactName": "Jane Smith",
        "organisationContactEmailAddress": "jane.smith@fintrust.co.za",
        "organisationContactPhoneNumber": "+27-11-987-6543",
        "organisationContactCellNumber": "+27-82-123-4567",
        "companySize": "Large",
        "numberOfEmployees": 1250,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Retail and Commercial Banking",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 4,
        "dateBusinessCommenced": "1995-03-15T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "Banking Association of South Africa",
        "ceoName": "Michael",
        "ceoSurname": "van der Merwe",
        "ceoEmail": "m.vandermerwe@fintrust.co.za",
        "ceoRaceId": "2",
        "ceoGenderId": "M",
        "seniorRepName": "Lerato",
        "seniorRepSurname": "Mokoena",
        "seniorRepEmail": "l.mokoena@fintrust.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "F",
        "id": 1
    },
    {
        "sdlNo": "SDL9876543210",
        "setaId": 205,
        "seta": "MerSETA",
        "sicCode": "4510",
        "organisationRegistrationNumber": "2008/987654/23",
        "organisationName": "AutoDrive Motors (Pty) Ltd",
        "organisationTradingName": "AutoDrive",
        "organisationFaxNumber": "+27-21-456-7890",
        "organisationContactName": null,
        "organisationContactEmailAddress": "info@autodrive.co.za",
        "organisationContactPhoneNumber": "+27-21-123-4567",
        "organisationContactCellNumber": "+27-83-987-6543",
        "companySize": "Medium",
        "numberOfEmployees": 85,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Vehicle Retail and Servicing",
        "parentSdlNumber": "SDL1234567890",
        "bbbeeStatus": "Non-Compliant",
        "bbbeeLevel": 0,
        "dateBusinessCommenced": "2008-11-02T00:00:00Z",
        "status": "Active",
        "exemptionCode": 5,
        "chamber": "National Automobile Dealers Association",
        "ceoName": "David",
        "ceoSurname": "Naidoo",
        "ceoEmail": "d.naidoo@autodrive.co.za",
        "ceoRaceId": "3",
        "ceoGenderId": "M",
        "seniorRepName": "Thandi",
        "seniorRepSurname": "Khumalo",
        "seniorRepEmail": "t.khumalo@autodrive.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "F",
        "id": 2
    },
    {
        "sdlNo": "SDL5556667778",
        "setaId": 302,
        "seta": "Services SETA",
        "sicCode": "7910",
        "organisationRegistrationNumber": "2015/445566/07",
        "organisationName": "Elite Hospitality Group",
        "organisationTradingName": "EliteStay",
        "organisationFaxNumber": "+27-31-222-3333",
        "organisationContactName": "Sarah Johnson",
        "organisationContactEmailAddress": "sarah@elitestay.co.za",
        "organisationContactPhoneNumber": "+27-31-444-5555",
        "organisationContactCellNumber": "+27-84-111-2222",
        "companySize": "Small",
        "numberOfEmployees": 42,
        "typeOfEntity": "CC (Close Corporation)",
        "coreBusiness": "Hotel and Accommodation Services",
        "parentSdlNumber": null,
        "bbbeeStatus": "Exempt",
        "bbbeeLevel": 0,
        "dateBusinessCommenced": "2015-07-20T00:00:00Z",
        "status": "Active",
        "exemptionCode": 2,
        "chamber": "South African Tourism",
        "ceoName": "Anita",
        "ceoSurname": "Reddy",
        "ceoEmail": "a.reddy@elitestay.co.za",
        "ceoRaceId": "4",
        "ceoGenderId": "F",
        "seniorRepName": "James",
        "seniorRepSurname": "Petersen",
        "seniorRepEmail": "j.petersen@elitestay.co.za",
        "seniorRepRaceId": "5",
        "seniorRepGenderId": "M",
        "id": 3
    },
    {
        "sdlNo": "SDL8889990001",
        "setaId": 107,
        "seta": "EWSETA",
        "sicCode": "3510",
        "organisationRegistrationNumber": "2010/778899/07",
        "organisationName": "GreenPower Solutions (Pty) Ltd",
        "organisationTradingName": "GreenPower",
        "organisationFaxNumber": "+27-12-666-7777",
        "organisationContactName": "Mark Williams",
        "organisationContactEmailAddress": "contact@greenpower.co.za",
        "organisationContactPhoneNumber": "+27-12-888-9999",
        "organisationContactCellNumber": "+27-81-333-4444",
        "companySize": "Medium",
        "numberOfEmployees": 112,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Renewable Energy Installation",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 5,
        "dateBusinessCommenced": "2010-09-10T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "South African Renewable Energy Council",
        "ceoName": "Sipho",
        "ceoSurname": "Dlamini",
        "ceoEmail": "s.dlamini@greenpower.co.za",
        "ceoRaceId": "1",
        "ceoGenderId": "M",
        "seniorRepName": "Nomsa",
        "seniorRepSurname": "Zulu",
        "seniorRepEmail": "n.zulu@greenpower.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "F",
        "id": 4
    },
    {
        "sdlNo": "SDL2223334445",
        "setaId": 401,
        "seta": "AGRISETA",
        "sicCode": "0111",
        "organisationRegistrationNumber": "1998/556677/23",
        "organisationName": "Golden Fields Farming Co",
        "organisationTradingName": "Golden Fields",
        "organisationFaxNumber": "+27-51-111-2222",
        "organisationContactName": null,
        "organisationContactEmailAddress": "info@goldenfields.co.za",
        "organisationContactPhoneNumber": "+27-51-333-4444",
        "organisationContactCellNumber": "+27-82-555-6666",
        "companySize": "Large",
        "numberOfEmployees": 320,
        "typeOfEntity": "Cooperative",
        "coreBusiness": "Maize and Wheat Farming",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 3,
        "dateBusinessCommenced": "1998-01-05T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "Agricultural Union of South Africa",
        "ceoName": "Kagiso",
        "ceoSurname": "Molefe",
        "ceoEmail": "k.molefe@goldenfields.co.za",
        "ceoRaceId": "1",
        "ceoGenderId": "M",
        "seniorRepName": "Elsabe",
        "seniorRepSurname": "Botha",
        "seniorRepEmail": "e.botha@goldenfields.co.za",
        "seniorRepRaceId": "2",
        "seniorRepGenderId": "F",
        "id": 5
    },
    {
        "sdlNo": "SDL6667778889",
        "setaId": 209,
        "seta": "CETA",
        "sicCode": "4100",
        "organisationRegistrationNumber": "2012/112233/07",
        "organisationName": "BuildRight Construction (Pty) Ltd",
        "organisationTradingName": "BuildRight",
        "organisationFaxNumber": "+27-11-777-8888",
        "organisationContactName": "Tanya Moodley",
        "organisationContactEmailAddress": "tanya@buildright.co.za",
        "organisationContactPhoneNumber": "+27-11-999-0000",
        "organisationContactCellNumber": "+27-83-777-8888",
        "companySize": "Medium",
        "numberOfEmployees": 95,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Residential Construction",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 6,
        "dateBusinessCommenced": "2012-05-17T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "Master Builders South Africa",
        "ceoName": "Raj",
        "ceoSurname": "Gandhi",
        "ceoEmail": "r.gandhi@buildright.co.za",
        "ceoRaceId": "4",
        "ceoGenderId": "M",
        "seniorRepName": "Zanele",
        "seniorRepSurname": "Khuzwayo",
        "seniorRepEmail": "z.khuzwayo@buildright.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "F",
        "id": 6
    },
    {
        "sdlNo": "SDL3334445556",
        "setaId": 503,
        "seta": "TETA",
        "sicCode": "4920",
        "organisationRegistrationNumber": "2005/334455/07",
        "organisationName": "TransLogistics SA (Pty) Ltd",
        "organisationTradingName": "TransLog",
        "organisationFaxNumber": "+27-10-222-3333",
        "organisationContactName": null,
        "organisationContactEmailAddress": "dispatch@translog.co.za",
        "organisationContactPhoneNumber": "+27-10-444-5555",
        "organisationContactCellNumber": "+27-81-222-3333",
        "companySize": "Large",
        "numberOfEmployees": 410,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Freight and Logistics",
        "parentSdlNumber": "SDL2223334445",
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 2,
        "dateBusinessCommenced": "2005-12-01T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "South African Freight Forwarders Association",
        "ceoName": "John",
        "ceoSurname": "Mashaba",
        "ceoEmail": "j.mashaba@translog.co.za",
        "ceoRaceId": "1",
        "ceoGenderId": "M",
        "seniorRepName": "Amina",
        "seniorRepSurname": "Hassan",
        "seniorRepEmail": "a.hassan@translog.co.za",
        "seniorRepRaceId": "3",
        "seniorRepGenderId": "F",
        "id": 7
    },
    {
        "sdlNo": "SDL9990001112",
        "setaId": 110,
        "seta": "FASSET",
        "sicCode": "6619",
        "organisationRegistrationNumber": "2017/990011/07",
        "organisationName": "EduFuture Consultants",
        "organisationTradingName": "EduFuture",
        "organisationFaxNumber": "+27-15-666-7777",
        "organisationContactName": "Dr. Linda Pretorius",
        "organisationContactEmailAddress": "linda@edufuture.co.za",
        "organisationContactPhoneNumber": "+27-15-888-9999",
        "organisationContactCellNumber": "+27-82-999-0000",
        "companySize": "Small",
        "numberOfEmployees": 18,
        "typeOfEntity": "Sole Proprietor",
        "coreBusiness": "Educational Training and Development",
        "parentSdlNumber": null,
        "bbbeeStatus": "Exempt",
        "bbbeeLevel": 0,
        "dateBusinessCommenced": "2017-02-28T00:00:00Z",
        "status": "Active",
        "exemptionCode": 3,
        "chamber": "South African Institute for Education",
        "ceoName": "Linda",
        "ceoSurname": "Pretorius",
        "ceoEmail": "l.pretorius@edufuture.co.za",
        "ceoRaceId": "2",
        "ceoGenderId": "F",
        "seniorRepName": "Linda",
        "seniorRepSurname": "Pretorius",
        "seniorRepEmail": "l.pretorius@edufuture.co.za",
        "seniorRepRaceId": "2",
        "seniorRepGenderId": "F",
        "id": 8
    },
    {
        "sdlNo": "SDL4445556667",
        "setaId": 600,
        "seta": "W&RSETA",
        "sicCode": "8610",
        "organisationRegistrationNumber": "2009/445566/07",
        "organisationName": "CapeMed Health Services",
        "organisationTradingName": "CapeMed",
        "organisationFaxNumber": "+27-21-121-2121",
        "organisationContactName": "Dr. Thabo Moloi",
        "organisationContactEmailAddress": "info@capemed.co.za",
        "organisationContactPhoneNumber": "+27-21-343-4343",
        "organisationContactCellNumber": "+27-83-565-6565",
        "companySize": "Medium",
        "numberOfEmployees": 76,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Private Healthcare Clinics",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 4,
        "dateBusinessCommenced": "2009-08-14T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "Private Healthcare Providers Association",
        "ceoName": "Thabo",
        "ceoSurname": "Moloi",
        "ceoEmail": "t.moloi@capemed.co.za",
        "ceoRaceId": "1",
        "ceoGenderId": "M",
        "seniorRepName": "Nandi",
        "seniorRepSurname": "Buthelezi",
        "seniorRepEmail": "n.buthelezi@capemed.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "F",
        "id": 9
    },
    {
        "sdlNo": "SDL7778889990",
        "setaId": 701,
        "seta": "MICT SETA",
        "sicCode": "6190",
        "organisationRegistrationNumber": "2020/778899/07",
        "organisationName": "TechNova Solutions (Pty) Ltd",
        "organisationTradingName": "TechNova",
        "organisationFaxNumber": "+27-11-878-7878",
        "organisationContactName": null,
        "organisationContactEmailAddress": "hello@technova.co.za",
        "organisationContactPhoneNumber": "+27-11-989-8989",
        "organisationContactCellNumber": "+27-81-112-2112",
        "companySize": "Small",
        "numberOfEmployees": 28,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Software Development and IT Consulting",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 5,
        "dateBusinessCommenced": "2020-10-01T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "Institute of Information Technology Professionals SA",
        "ceoName": "Chen",
        "ceoSurname": "Wang",
        "ceoEmail": "c.wang@technova.co.za",
        "ceoRaceId": "4",
        "ceoGenderId": "M",
        "seniorRepName": "Ayanda",
        "seniorRepSurname": "Nkosi",
        "seniorRepEmail": "a.nkosi@technova.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "M",
        "id": 10
    }
];