import { BankDetail } from "../models/BankDto";
import { DiscretionaryGrantApplication, DiscretionaryProjectDetailsApproval, DiscretionaryProjectDto } from "../models/DiscretionaryDto";
import { OrganisationDto } from "../models/organizationDto";
import type {
    MandatoryApplicationDto,
    OrganisationPhysicalAddressDto,
    OrganisationPostalAddressDto,
    DocumentDto,
    MandatoryGrantPaymentDto,
    MandatoryGrantBiodataDto,
} from '@/core/models/MandatoryDto';


export const org_data: OrganisationDto[] = [
    {
        "sdlNo": "SDL1234567890",
        "setaId": 101,
        "seta": "BankSETA",
        "sicCode": "6411",
        "organisationRegistrationNumber": "1995/012345/07",
        "organisationName": "FinTrust Bank Ltd",
        "organisationTradingName": "FinTrust",
        "organisationFaxNumber": "+27-11-123-4567",
        "organisationContactName": "Jane Smith",
        "organisationContactEmailAddress": "jane.smith@fintrust.co.za",
        "organisationContactPhoneNumber": "+27-11-987-6543",
        "organisationContactCellNumber": "+27-82-123-4567",
        "companySize": "Large",
        "numberOfEmployees": 1250,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Retail and Commercial Banking",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 4,
        "dateBusinessCommenced": "1995-03-15T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "Banking Association of South Africa",
        "ceoName": "Michael",
        "ceoSurname": "van der Merwe",
        "ceoEmail": "m.vandermerwe@fintrust.co.za",
        "ceoRaceId": "2",
        "ceoGenderId": "M",
        "seniorRepName": "Lerato",
        "seniorRepSurname": "Mokoena",
        "seniorRepEmail": "l.mokoena@fintrust.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "F",
        "id": 1
    },
    {
        "sdlNo": "SDL9876543210",
        "setaId": 205,
        "seta": "MerSETA",
        "sicCode": "4510",
        "organisationRegistrationNumber": "2008/987654/23",
        "organisationName": "AutoDrive Motors (Pty) Ltd",
        "organisationTradingName": "AutoDrive",
        "organisationFaxNumber": "+27-21-456-7890",
        "organisationContactName": null,
        "organisationContactEmailAddress": "info@autodrive.co.za",
        "organisationContactPhoneNumber": "+27-21-123-4567",
        "organisationContactCellNumber": "+27-83-987-6543",
        "companySize": "Medium",
        "numberOfEmployees": 85,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Vehicle Retail and Servicing",
        "parentSdlNumber": "SDL1234567890",
        "bbbeeStatus": "Non-Compliant",
        "bbbeeLevel": 0,
        "dateBusinessCommenced": "2008-11-02T00:00:00Z",
        "status": "Active",
        "exemptionCode": 5,
        "chamber": "National Automobile Dealers Association",
        "ceoName": "David",
        "ceoSurname": "Naidoo",
        "ceoEmail": "d.naidoo@autodrive.co.za",
        "ceoRaceId": "3",
        "ceoGenderId": "M",
        "seniorRepName": "Thandi",
        "seniorRepSurname": "Khumalo",
        "seniorRepEmail": "t.khumalo@autodrive.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "F",
        "id": 2
    },
    {
        "sdlNo": "SDL5556667778",
        "setaId": 302,
        "seta": "Services SETA",
        "sicCode": "7910",
        "organisationRegistrationNumber": "2015/445566/07",
        "organisationName": "Elite Hospitality Group",
        "organisationTradingName": "EliteStay",
        "organisationFaxNumber": "+27-31-222-3333",
        "organisationContactName": "Sarah Johnson",
        "organisationContactEmailAddress": "sarah@elitestay.co.za",
        "organisationContactPhoneNumber": "+27-31-444-5555",
        "organisationContactCellNumber": "+27-84-111-2222",
        "companySize": "Small",
        "numberOfEmployees": 42,
        "typeOfEntity": "CC (Close Corporation)",
        "coreBusiness": "Hotel and Accommodation Services",
        "parentSdlNumber": null,
        "bbbeeStatus": "Exempt",
        "bbbeeLevel": 0,
        "dateBusinessCommenced": "2015-07-20T00:00:00Z",
        "status": "Active",
        "exemptionCode": 2,
        "chamber": "South African Tourism",
        "ceoName": "Anita",
        "ceoSurname": "Reddy",
        "ceoEmail": "a.reddy@elitestay.co.za",
        "ceoRaceId": "4",
        "ceoGenderId": "F",
        "seniorRepName": "James",
        "seniorRepSurname": "Petersen",
        "seniorRepEmail": "j.petersen@elitestay.co.za",
        "seniorRepRaceId": "5",
        "seniorRepGenderId": "M",
        "id": 3
    },
    {
        "sdlNo": "SDL8889990001",
        "setaId": 107,
        "seta": "EWSETA",
        "sicCode": "3510",
        "organisationRegistrationNumber": "2010/778899/07",
        "organisationName": "GreenPower Solutions (Pty) Ltd",
        "organisationTradingName": "GreenPower",
        "organisationFaxNumber": "+27-12-666-7777",
        "organisationContactName": "Mark Williams",
        "organisationContactEmailAddress": "contact@greenpower.co.za",
        "organisationContactPhoneNumber": "+27-12-888-9999",
        "organisationContactCellNumber": "+27-81-333-4444",
        "companySize": "Medium",
        "numberOfEmployees": 112,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Renewable Energy Installation",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 5,
        "dateBusinessCommenced": "2010-09-10T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "South African Renewable Energy Council",
        "ceoName": "Sipho",
        "ceoSurname": "Dlamini",
        "ceoEmail": "s.dlamini@greenpower.co.za",
        "ceoRaceId": "1",
        "ceoGenderId": "M",
        "seniorRepName": "Nomsa",
        "seniorRepSurname": "Zulu",
        "seniorRepEmail": "n.zulu@greenpower.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "F",
        "id": 4
    },
    {
        "sdlNo": "SDL2223334445",
        "setaId": 401,
        "seta": "AGRISETA",
        "sicCode": "0111",
        "organisationRegistrationNumber": "1998/556677/23",
        "organisationName": "Golden Fields Farming Co",
        "organisationTradingName": "Golden Fields",
        "organisationFaxNumber": "+27-51-111-2222",
        "organisationContactName": null,
        "organisationContactEmailAddress": "info@goldenfields.co.za",
        "organisationContactPhoneNumber": "+27-51-333-4444",
        "organisationContactCellNumber": "+27-82-555-6666",
        "companySize": "Large",
        "numberOfEmployees": 320,
        "typeOfEntity": "Cooperative",
        "coreBusiness": "Maize and Wheat Farming",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 3,
        "dateBusinessCommenced": "1998-01-05T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "Agricultural Union of South Africa",
        "ceoName": "Kagiso",
        "ceoSurname": "Molefe",
        "ceoEmail": "k.molefe@goldenfields.co.za",
        "ceoRaceId": "1",
        "ceoGenderId": "M",
        "seniorRepName": "Elsabe",
        "seniorRepSurname": "Botha",
        "seniorRepEmail": "e.botha@goldenfields.co.za",
        "seniorRepRaceId": "2",
        "seniorRepGenderId": "F",
        "id": 5
    },
    {
        "sdlNo": "SDL6667778889",
        "setaId": 209,
        "seta": "CETA",
        "sicCode": "4100",
        "organisationRegistrationNumber": "2012/112233/07",
        "organisationName": "BuildRight Construction (Pty) Ltd",
        "organisationTradingName": "BuildRight",
        "organisationFaxNumber": "+27-11-777-8888",
        "organisationContactName": "Tanya Moodley",
        "organisationContactEmailAddress": "tanya@buildright.co.za",
        "organisationContactPhoneNumber": "+27-11-999-0000",
        "organisationContactCellNumber": "+27-83-777-8888",
        "companySize": "Medium",
        "numberOfEmployees": 95,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Residential Construction",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 6,
        "dateBusinessCommenced": "2012-05-17T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "Master Builders South Africa",
        "ceoName": "Raj",
        "ceoSurname": "Gandhi",
        "ceoEmail": "r.gandhi@buildright.co.za",
        "ceoRaceId": "4",
        "ceoGenderId": "M",
        "seniorRepName": "Zanele",
        "seniorRepSurname": "Khuzwayo",
        "seniorRepEmail": "z.khuzwayo@buildright.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "F",
        "id": 6
    },
    {
        "sdlNo": "SDL3334445556",
        "setaId": 503,
        "seta": "TETA",
        "sicCode": "4920",
        "organisationRegistrationNumber": "2005/334455/07",
        "organisationName": "TransLogistics SA (Pty) Ltd",
        "organisationTradingName": "TransLog",
        "organisationFaxNumber": "+27-10-222-3333",
        "organisationContactName": null,
        "organisationContactEmailAddress": "dispatch@translog.co.za",
        "organisationContactPhoneNumber": "+27-10-444-5555",
        "organisationContactCellNumber": "+27-81-222-3333",
        "companySize": "Large",
        "numberOfEmployees": 410,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Freight and Logistics",
        "parentSdlNumber": "SDL2223334445",
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 2,
        "dateBusinessCommenced": "2005-12-01T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "South African Freight Forwarders Association",
        "ceoName": "John",
        "ceoSurname": "Mashaba",
        "ceoEmail": "j.mashaba@translog.co.za",
        "ceoRaceId": "1",
        "ceoGenderId": "M",
        "seniorRepName": "Amina",
        "seniorRepSurname": "Hassan",
        "seniorRepEmail": "a.hassan@translog.co.za",
        "seniorRepRaceId": "3",
        "seniorRepGenderId": "F",
        "id": 7
    },
    {
        "sdlNo": "SDL9990001112",
        "setaId": 110,
        "seta": "FASSET",
        "sicCode": "6619",
        "organisationRegistrationNumber": "2017/990011/07",
        "organisationName": "EduFuture Consultants",
        "organisationTradingName": "EduFuture",
        "organisationFaxNumber": "+27-15-666-7777",
        "organisationContactName": "Dr. Linda Pretorius",
        "organisationContactEmailAddress": "linda@edufuture.co.za",
        "organisationContactPhoneNumber": "+27-15-888-9999",
        "organisationContactCellNumber": "+27-82-999-0000",
        "companySize": "Small",
        "numberOfEmployees": 18,
        "typeOfEntity": "Sole Proprietor",
        "coreBusiness": "Educational Training and Development",
        "parentSdlNumber": null,
        "bbbeeStatus": "Exempt",
        "bbbeeLevel": 0,
        "dateBusinessCommenced": "2017-02-28T00:00:00Z",
        "status": "Active",
        "exemptionCode": 3,
        "chamber": "South African Institute for Education",
        "ceoName": "Linda",
        "ceoSurname": "Pretorius",
        "ceoEmail": "l.pretorius@edufuture.co.za",
        "ceoRaceId": "2",
        "ceoGenderId": "F",
        "seniorRepName": "Linda",
        "seniorRepSurname": "Pretorius",
        "seniorRepEmail": "l.pretorius@edufuture.co.za",
        "seniorRepRaceId": "2",
        "seniorRepGenderId": "F",
        "id": 8
    },
    {
        "sdlNo": "SDL4445556667",
        "setaId": 600,
        "seta": "W&RSETA",
        "sicCode": "8610",
        "organisationRegistrationNumber": "2009/445566/07",
        "organisationName": "CapeMed Health Services",
        "organisationTradingName": "CapeMed",
        "organisationFaxNumber": "+27-21-121-2121",
        "organisationContactName": "Dr. Thabo Moloi",
        "organisationContactEmailAddress": "info@capemed.co.za",
        "organisationContactPhoneNumber": "+27-21-343-4343",
        "organisationContactCellNumber": "+27-83-565-6565",
        "companySize": "Medium",
        "numberOfEmployees": 76,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Private Healthcare Clinics",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 4,
        "dateBusinessCommenced": "2009-08-14T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "Private Healthcare Providers Association",
        "ceoName": "Thabo",
        "ceoSurname": "Moloi",
        "ceoEmail": "t.moloi@capemed.co.za",
        "ceoRaceId": "1",
        "ceoGenderId": "M",
        "seniorRepName": "Nandi",
        "seniorRepSurname": "Buthelezi",
        "seniorRepEmail": "n.buthelezi@capemed.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "F",
        "id": 9
    },
    {
        "sdlNo": "SDL7778889990",
        "setaId": 701,
        "seta": "MICT SETA",
        "sicCode": "6190",
        "organisationRegistrationNumber": "2020/778899/07",
        "organisationName": "TechNova Solutions (Pty) Ltd",
        "organisationTradingName": "TechNova",
        "organisationFaxNumber": "+27-11-878-7878",
        "organisationContactName": null,
        "organisationContactEmailAddress": "hello@technova.co.za",
        "organisationContactPhoneNumber": "+27-11-989-8989",
        "organisationContactCellNumber": "+27-81-112-2112",
        "companySize": "Small",
        "numberOfEmployees": 28,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Software Development and IT Consulting",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 5,
        "dateBusinessCommenced": "2020-10-01T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "Institute of Information Technology Professionals SA",
        "ceoName": "Chen",
        "ceoSurname": "Wang",
        "ceoEmail": "c.wang@technova.co.za",
        "ceoRaceId": "4",
        "ceoGenderId": "M",
        "seniorRepName": "Ayanda",
        "seniorRepSurname": "Nkosi",
        "seniorRepEmail": "a.nkosi@technova.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "M",
        "id": 10
    }
];

export const mockDiscretionaryProjectDetailsApprovals: DiscretionaryProjectDetailsApproval[] = [
    {
        id: 1,
        projectId: 101,
        projectTypeId: 2,
        applicationStatusId: 3,
        submittedBy: "john.doe@chieta.org",
        submissionDte: "2024-11-15T10:30:00Z",
        currentApprover: "Jane Smith",
        contractNumber: "CT-2024-DISC-001",
        reason: "Skills development for youth in rural areas",
        approvalStatus: "Pending",
        focusAreaId: 5,
        subCategoryId: 12,
        interventionId: 7,
        otherIntervention: null,
        focusCritEvalId: 4,
        numberContinuing: 30,
        numberNew: 70,
        costPerLearner: 4500.0,
        gecNew: 20,
        gecContinuing: 10,
        gecCostPerLearner: 5000.0,
        gacNew: 15,
        gacContinuing: 8,
        gacCostPerLearner: 4800.0,
        gcNew: 35,
        gcContinuing: 12,
        gcCostPerLearner: 4600.0,
        hdi: 0.65,
        female: 42,
        youth: 58,
        numberDisabled: 5,
        rural: 25,
        province: "Gauteng",
        municipality: "City of Johannesburg",
        district: "Region F",
        vision2025goal: "Increase youth employability through accredited training",
        sqmrAppIndicator: true,
        leviesUptodate: true,
        previousWsp: "2023-WSP-CHIETA-889",
        previousParticipation: "Yes – 2022 Discretionary Grant",
        dateCreated: "2024-11-15T09:15:00Z",
        userId: "user_789",
        usrUpd: "admin_user",
        dteUpd: "2024-11-16T14:20:00Z",
        comments: "Strong alignment with rural development goals.",
        companyTypeId: 1,
        companyComplianceId: 3,
        discLearnerTypeId: 2,
        hiStoricalPerfomanceId: 5,
        newCompany: false,
        linkToSsp: "https://ssp.chieta.org.za/project/101"
    },
    {
        id: 2,
        projectId: 102,
        projectTypeId: 1,
        applicationStatusId: 2,
        submittedBy: "sarah.lee@skillsdev.co.za",
        submissionDte: "2024-12-01T08:45:00Z",
        currentApprover: null,
        contractNumber: null,
        reason: "Upskilling employees in green energy sector",
        approvalStatus: "Submitted",
        focusAreaId: 3,
        subCategoryId: 8,
        interventionId: 9,
        otherIntervention: "Renewable energy technician training",
        focusCritEvalId: 2,
        numberContinuing: 0,
        numberNew: 50,
        costPerLearner: 6200.0,
        gecNew: 50,
        gecContinuing: 0,
        gecCostPerLearner: 6200.0,
        gacNew: 45,
        gacContinuing: 0,
        gacCostPerLearner: 6100.0,
        gcNew: 50,
        gcContinuing: 0,
        gcCostPerLearner: 6150.0,
        hdi: 0.72,
        female: 30,
        youth: 40,
        numberDisabled: 2,
        rural: 0,
        province: "Western Cape",
        municipality: "City of Cape Town",
        district: "Southern Suburbs",
        vision2025goal: "Support just energy transition",
        sqmrAppIndicator: true,
        leviesUptodate: true,
        previousWsp: null,
        previousParticipation: "No",
        dateCreated: "2024-12-01T08:30:00Z",
        userId: "user_456",
        usrUpd: null,
        dteUpd: null,
        comments: null,
        companyTypeId: 2,
        companyComplianceId: 1,
        discLearnerTypeId: 1,
        hiStoricalPerfomanceId: 4,
        newCompany: true,
        linkToSsp: null
    },
    {
        id: 3,
        projectId: 103,
        projectTypeId: 3,
        applicationStatusId: 4,
        submittedBy: "michael.ngo@edutrain.org",
        submissionDte: "2024-10-20T14:20:00Z",
        currentApprover: "David van der Merwe",
        contractNumber: "CT-2024-DISC-003",
        reason: "Digital literacy for women in informal settlements",
        approvalStatus: "Approved",
        focusAreaId: 2,
        subCategoryId: 5,
        interventionId: 4,
        otherIntervention: null,
        focusCritEvalId: 3,
        numberContinuing: 20,
        numberNew: 80,
        costPerLearner: 3200.0,
        gecNew: 60,
        gecContinuing: 15,
        gecCostPerLearner: 3400.0,
        gacNew: 55,
        gacContinuing: 10,
        gacCostPerLearner: 3300.0,
        gcNew: 70,
        gcContinuing: 18,
        gcCostPerLearner: 3250.0,
        hdi: 0.58,
        female: 75,
        youth: 65,
        numberDisabled: 8,
        rural: 12,
        province: "KwaZulu-Natal",
        municipality: "eThekwini",
        district: "Durban Central",
        vision2025goal: "Bridge gender digital divide",
        sqmrAppIndicator: true,
        leviesUptodate: false,
        previousWsp: "2023-WSP-CHIETA-455",
        previousParticipation: "Yes – 2021",
        dateCreated: "2024-10-20T13:00:00Z",
        userId: "user_222",
        usrUpd: "approver_01",
        dteUpd: "2024-10-25T09:10:00Z",
        comments: "Approved with condition: submit quarterly impact reports.",
        companyTypeId: 3,
        companyComplianceId: 2,
        discLearnerTypeId: 3,
        hiStoricalPerfomanceId: 6,
        newCompany: false,
        linkToSsp: "https://ssp.chieta.org.za/project/103"
    },
    {
        id: 4,
        projectId: 104,
        projectTypeId: 2,
        applicationStatusId: 1,
        submittedBy: "admin@techfuture.co.za",
        submissionDte: "2025-01-05T11:15:00Z",
        currentApprover: null,
        contractNumber: null,
        reason: "AI and data science upskilling for SMEs",
        approvalStatus: "Draft",
        focusAreaId: 6,
        subCategoryId: 15,
        interventionId: 11,
        otherIntervention: "Machine learning certification",
        focusCritEvalId: 5,
        numberContinuing: 10,
        numberNew: 40,
        costPerLearner: 8900.0,
        gecNew: 30,
        gecContinuing: 5,
        gecCostPerLearner: 9000.0,
        gacNew: 28,
        gacContinuing: 4,
        gacCostPerLearner: 8800.0,
        gcNew: 35,
        gcContinuing: 6,
        gcCostPerLearner: 8950.0,
        hdi: 0.81,
        female: 25,
        youth: 70,
        numberDisabled: 0,
        rural: 5,
        province: "Gauteng",
        municipality: "City of Tshwane",
        district: "Pretoria East",
        vision2025goal: "Build future-ready tech talent",
        sqmrAppIndicator: null,
        leviesUptodate: true,
        previousWsp: null,
        previousParticipation: "No",
        dateCreated: "2025-01-05T10:00:00Z",
        userId: "user_999",
        usrUpd: null,
        dteUpd: null,
        comments: null,
        companyTypeId: 1,
        companyComplianceId: 1,
        discLearnerTypeId: 1,
        hiStoricalPerfomanceId: 2,
        newCompany: true,
        linkToSsp: null
    },
    {
        id: 5,
        projectId: 105,
        projectTypeId: 4,
        applicationStatusId: 3,
        submittedBy: "nomsa.khumalo@agripro.co.za",
        submissionDte: "2024-12-18T09:30:00Z",
        currentApprover: "Thandi Naidoo",
        contractNumber: null,
        reason: "Agricultural mechanization training for smallholders",
        approvalStatus: "Pending",
        focusAreaId: 1,
        subCategoryId: 3,
        interventionId: 2,
        otherIntervention: null,
        focusCritEvalId: 1,
        numberContinuing: 25,
        numberNew: 45,
        costPerLearner: 5400.0,
        gecNew: 35,
        gecContinuing: 20,
        gecCostPerLearner: 5500.0,
        gacNew: 30,
        gacContinuing: 18,
        gacCostPerLearner: 5300.0,
        gcNew: 40,
        gcContinuing: 22,
        gcCostPerLearner: 5350.0,
        hdi: 0.52,
        female: 50,
        youth: 30,
        numberDisabled: 3,
        rural: 40,
        province: "Limpopo",
        municipality: "Vhembe",
        district: "Thohoyandou",
        vision2025goal: "Enhance food security through modern farming",
        sqmrAppIndicator: true,
        leviesUptodate: true,
        previousWsp: "2023-WSP-CHIETA-771",
        previousParticipation: "Yes – 2023",
        dateCreated: "2024-12-18T08:45:00Z",
        userId: "user_555",
        usrUpd: null,
        dteUpd: null,
        comments: "Awaiting budget confirmation from finance.",
        companyTypeId: 4,
        companyComplianceId: 3,
        discLearnerTypeId: 4,
        hiStoricalPerfomanceId: 7,
        newCompany: false,
        linkToSsp: null
    },
    {
        id: 6,
        projectId: 106,
        projectTypeId: 2,
        applicationStatusId: 5,
        submittedBy: "robert.mokoena@buildskills.co.za",
        submissionDte: "2024-09-10T13:45:00Z",
        currentApprover: "Sipho Dlamini",
        contractNumber: "CT-2024-DISC-006",
        reason: "Construction safety and scaffolding certification",
        approvalStatus: "Rejected",
        focusAreaId: 4,
        subCategoryId: 10,
        interventionId: 6,
        otherIntervention: null,
        focusCritEvalId: 6,
        numberContinuing: 15,
        numberNew: 35,
        costPerLearner: 4100.0,
        gecNew: 25,
        gecContinuing: 10,
        gecCostPerLearner: 4200.0,
        gacNew: 20,
        gacContinuing: 8,
        gacCostPerLearner: 4000.0,
        gcNew: 30,
        gcContinuing: 12,
        gcCostPerLearner: 4050.0,
        hdi: 0.60,
        female: 10,
        youth: 50,
        numberDisabled: 1,
        rural: 20,
        province: "Eastern Cape",
        municipality: "Buffalo City",
        district: "East London",
        vision2025goal: "Improve workplace safety in construction",
        sqmrAppIndicator: false,
        leviesUptodate: false,
        previousWsp: "2022-WSP-CHIETA-333",
        previousParticipation: "Yes – 2022",
        dateCreated: "2024-09-10T12:30:00Z",
        userId: "user_333",
        usrUpd: "reviewer_02",
        dteUpd: "2024-09-20T16:00:00Z",
        comments: "Rejected: levy payments overdue and incomplete WSP submission.",
        companyTypeId: 2,
        companyComplianceId: 5,
        discLearnerTypeId: 2,
        hiStoricalPerfomanceId: 3,
        newCompany: false,
        linkToSsp: null
    },
    {
        id: 7,
        projectId: 107,
        projectTypeId: 1,
        applicationStatusId: 3,
        submittedBy: "lerato.maleka@healthfirst.org",
        submissionDte: "2025-01-10T10:00:00Z",
        currentApprover: "Dr. Nomvula Maseko",
        contractNumber: null,
        reason: "Community health worker training in TB and HIV",
        approvalStatus: "Pending",
        focusAreaId: 7,
        subCategoryId: 18,
        interventionId: 13,
        otherIntervention: "Mobile clinic support",
        focusCritEvalId: 7,
        numberContinuing: 40,
        numberNew: 60,
        costPerLearner: 3800.0,
        gecNew: 50,
        gecContinuing: 30,
        gecCostPerLearner: 3900.0,
        gacNew: 45,
        gacContinuing: 25,
        gacCostPerLearner: 3750.0,
        gcNew: 55,
        gcContinuing: 35,
        gcCostPerLearner: 3800.0,
        hdi: 0.55,
        female: 85,
        youth: 45,
        numberDisabled: 4,
        rural: 50,
        province: "Mpumalanga",
        municipality: "Ehlanzeni",
        district: "Nelspruit",
        vision2025goal: "Strengthen primary healthcare access",
        sqmrAppIndicator: true,
        leviesUptodate: true,
        previousWsp: "2023-WSP-CHIETA-999",
        previousParticipation: "Yes – 2020, 2022",
        dateCreated: "2025-01-10T09:15:00Z",
        userId: "user_777",
        usrUpd: null,
        dteUpd: null,
        comments: "High priority due to disease burden in region.",
        companyTypeId: 5,
        companyComplianceId: 2,
        discLearnerTypeId: 5,
        hiStoricalPerfomanceId: 8,
        newCompany: false,
        linkToSsp: null
    },
    {
        id: 8,
        projectId: 108,
        projectTypeId: 3,
        applicationStatusId: 4,
        submittedBy: "james.petersen@techacademy.co.za",
        submissionDte: "2024-11-30T15:20:00Z",
        currentApprover: "Anita Reddy",
        contractNumber: "CT-2024-DISC-008",
        reason: "Coding bootcamp for unemployed graduates",
        approvalStatus: "Approved",
        focusAreaId: 6,
        subCategoryId: 14,
        interventionId: 10,
        otherIntervention: null,
        focusCritEvalId: 5,
        numberContinuing: 0,
        numberNew: 100,
        costPerLearner: 7500.0,
        gecNew: 80,
        gecContinuing: 0,
        gecCostPerLearner: 7600.0,
        gacNew: 70,
        gacContinuing: 0,
        gacCostPerLearner: 7400.0,
        gcNew: 90,
        gcContinuing: 0,
        gcCostPerLearner: 7500.0,
        hdi: 0.78,
        female: 40,
        youth: 95,
        numberDisabled: 5,
        rural: 15,
        province: "Gauteng",
        municipality: "Ekurhuleni",
        district: "East Rand",
        vision2025goal: "Reduce graduate unemployment through tech skills",
        sqmrAppIndicator: true,
        leviesUptodate: true,
        previousWsp: "2023-WSP-CHIETA-112",
        previousParticipation: "Yes – 2023",
        dateCreated: "2024-11-30T14:00:00Z",
        userId: "user_888",
        usrUpd: "approver_03",
        dteUpd: "2024-12-05T11:30:00Z",
        comments: "Approved. Partner with 3 local universities for placement.",
        companyTypeId: 1,
        companyComplianceId: 1,
        discLearnerTypeId: 1,
        hiStoricalPerfomanceId: 9,
        newCompany: false,
        linkToSsp: "https://ssp.chieta.org.za/project/108"
    },
    {
        id: 9,
        projectId: 109,
        projectTypeId: 2,
        applicationStatusId: 2,
        submittedBy: "thabo.molefe@agritech.co.za",
        submissionDte: "2025-01-15T09:10:00Z",
        currentApprover: null,
        contractNumber: null,
        reason: "Drone operation and precision agriculture",
        approvalStatus: "Submitted",
        focusAreaId: 1,
        subCategoryId: 4,
        interventionId: 3,
        otherIntervention: "Drone pilot certification",
        focusCritEvalId: 1,
        numberContinuing: 5,
        numberNew: 25,
        costPerLearner: 12000.0,
        gecNew: 20,
        gecContinuing: 3,
        gecCostPerLearner: 12500.0,
        gacNew: 18,
        gacContinuing: 2,
        gacCostPerLearner: 11800.0,
        gcNew: 22,
        gcContinuing: 4,
        gcCostPerLearner: 12000.0,
        hdi: 0.62,
        female: 20,
        youth: 60,
        numberDisabled: 0,
        rural: 22,
        province: "North West",
        municipality: "Ngaka Modiri Molema",
        district: "Mahikeng",
        vision2025goal: "Modernize small-scale farming with technology",
        sqmrAppIndicator: true,
        leviesUptodate: true,
        previousWsp: null,
        previousParticipation: "No",
        dateCreated: "2025-01-15T08:30:00Z",
        userId: "user_123",
        usrUpd: null,
        dteUpd: null,
        comments: null,
        companyTypeId: 2,
        companyComplianceId: 2,
        discLearnerTypeId: 2,
        hiStoricalPerfomanceId: 1,
        newCompany: true,
        linkToSsp: null
    },
    {
        id: 10,
        projectId: 110,
        projectTypeId: 4,
        applicationStatusId: 3,
        submittedBy: "zanele.khumalo@textileskills.co.za",
        submissionDte: "2024-12-20T12:00:00Z",
        currentApprover: "Raj Gandhi",
        contractNumber: null,
        reason: "Apparel manufacturing and design for women cooperatives",
        approvalStatus: "Pending",
        focusAreaId: 8,
        subCategoryId: 20,
        interventionId: 15,
        otherIntervention: "Sustainable fabric sourcing",
        focusCritEvalId: 8,
        numberContinuing: 30,
        numberNew: 70,
        costPerLearner: 4200.0,
        gecNew: 60,
        gecContinuing: 25,
        gecCostPerLearner: 4300.0,
        gacNew: 55,
        gacContinuing: 20,
        gacCostPerLearner: 4100.0,
        gcNew: 65,
        gcContinuing: 28,
        gcCostPerLearner: 4200.0,
        hdi: 0.59,
        female: 100,
        youth: 55,
        numberDisabled: 6,
        rural: 35,
        province: "KwaZulu-Natal",
        municipality: "uMgungundlovu",
        district: "Pietermaritzburg",
        vision2025goal: "Empower women through sustainable fashion",
        sqmrAppIndicator: true,
        leviesUptodate: true,
        previousWsp: "2023-WSP-CHIETA-555",
        previousParticipation: "Yes – 2021, 2023",
        dateCreated: "2024-12-20T11:15:00Z",
        userId: "user_444",
        usrUpd: null,
        dteUpd: null,
        comments: "Awaiting site verification report.",
        companyTypeId: 3,
        companyComplianceId: 3,
        discLearnerTypeId: 6,
        hiStoricalPerfomanceId: 10,
        newCompany: false,
        linkToSsp: null
    }
];

export const sampleDiscretionaryGrantApplications: DiscretionaryGrantApplication[] = [
    {
        id: 1001,
        sdl: "1234567890",
        organisationId: 501,
        organisation_Name: "TechSkills Academy (Pty) Ltd",
        organisation_Trade_Name: "TechSkills",
        contract_Number: "CHI-DG-2025-1001",
        projectId: 2001,
        applicationStatusId: 44,
        projectType: "Learnership",
        project: "ICT Support Practitioner Learnership",
        focusArea: "Digital Skills",
        subCategory: "Information Technology",
        intervention: "Learnership",
        otherIntervention: null,
        number_Continuing: 15,
        number_New: 35,
        costPerLearner: 24500,
        geC_Continuing: 10,
        geC_New: 25,
        geC_CostPerLearner: 22000,
        gaC_Continuing: 3,
        gaC_New: 8,
        gaC_CostPerLearner: 30000,
        gC_Continuing: 2,
        gC_New: 2,
        gC_CostPerLearner: 40000,
        hdi: 78,
        female: 22,
        youth: 38,
        number_Disabled: 3,
        rural: 8,
        province: "Gauteng",
        municipality: "City of Johannesburg",
        status: "Approved",
        sqmrAppIndicator: "Yes",
        vision2025goal: "Increase digital inclusion",
        leviesuptodate: "Yes",
        previousWSP: "2024/25",
        previousParticipation: "Yes – 2023 DG Cycle",
        approvalStatus: {
            id: 101,
            applicationId: 1001,
            approvalTypeId: 1,
            approvalStatusId: 108,
            comments: "Fully compliant; GEC & GAC approvals secured.",
            dateCreated: "2025-03-12T09:20:15Z",
            userId: 205,
            dteUpd: "2025-04-01T14:10:30Z",
            userUpd: 210
        },
        gecStatus: {
            id: 102,
            applicationId: 1001,
            approvalTypeId: 2,
            approvalStatusId: 86,
            comments: "GEC Committee Review Completed",
            dateCreated: "2025-03-10T11:05:22Z",
            userId: 206,
            dteUpd: "2025-03-10T11:05:22Z",
            userUpd: 206
        },
        gacStatus: {
            id: 103,
            applicationId: 1001,
            approvalTypeId: 3,
            approvalStatusId: 86,
            comments: "GAC Committee Review Completed",
            dateCreated: "2025-03-15T13:45:10Z",
            userId: 207,
            dteUpd: "2025-03-15T13:45:10Z",
            userUpd: 207
        },
        gcStatus: {
            id: 104,
            applicationId: 1001,
            approvalTypeId: 4,
            approvalStatusId: 86,
            comments: "GC Committee Review Completed",
            dateCreated: "2025-03-18T10:30:00Z",
            userId: 208,
            dteUpd: "2025-03-18T10:30:00Z",
            userUpd: 208
        },
        comment: "Strong alignment with sector needs; high youth & female participation.",
        dateCreated: "2025-03-05T08:00:00Z"
    },
    {
        id: 1002,
        sdl: "9876543210",
        organisationId: 502,
        organisation_Name: "GreenBuild Training Institute",
        organisation_Trade_Name: "GreenBuild",
        contract_Number: "CHI-DG-2025-1002",
        projectId: 2002,
        applicationStatusId: 55,
        projectType: "Skills Programme",
        project: "Green Building Assessor",
        focusArea: "Green Economy",
        subCategory: "Construction & Built Environment",
        intervention: "Skills Programme",
        otherIntervention: null,
        number_Continuing: 0,
        number_New: 20,
        costPerLearner: 18500,
        geC_Continuing: 0,
        geC_New: 12,
        geC_CostPerLearner: 16000,
        gaC_Continuing: 0,
        gaC_New: 5,
        gaC_CostPerLearner: 22000,
        gC_Continuing: 0,
        gC_New: 3,
        gC_CostPerLearner: 28000,
        hdi: 65,
        female: 9,
        youth: 14,
        number_Disabled: 1,
        rural: 11,
        province: "Eastern Cape",
        municipality: "Buffalo City",
        status: "Contract Signed",
        sqmrAppIndicator: "Yes",
        vision2025goal: "Sustainable infrastructure development",
        leviesuptodate: "Yes",
        previousWSP: "2024/25",
        previousParticipation: "No",
        approvalStatus: {
            id: 105,
            applicationId: 1002,
            approvalTypeId: 1,
            approvalStatusId: 111,
            comments: "Contract returned and signed.",
            dateCreated: "2025-03-20T16:40:00Z",
            userId: 205,
            dteUpd: "2025-03-21T09:15:12Z",
            userUpd: 209
        },
        gecStatus: {
            id: 106,
            applicationId: 1002,
            approvalTypeId: 2,
            approvalStatusId: 86,
            comments: "RSA Review Completed",
            dateCreated: "2025-02-28T10:20:00Z",
            userId: 206,
            dteUpd: "2025-02-28T10:20:00Z",
            userUpd: 206
        },
        gacStatus: {
            id: 107,
            applicationId: 1002,
            approvalTypeId: 3,
            approvalStatusId: 86,
            comments: "Regional Review Completed",
            dateCreated: "2025-03-05T14:30:45Z",
            userId: 207,
            dteUpd: "2025-03-05T14:30:45Z",
            userUpd: 207
        },
        gcStatus: {
            id: 108,
            applicationId: 1002,
            approvalTypeId: 4,
            approvalStatusId: 86,
            comments: "GEC Committee Review Completed",
            dateCreated: "2025-03-12T11:25:30Z",
            userId: 208,
            dteUpd: "2025-03-12T11:25:30Z",
            userUpd: 208
        },
        comment: "High rural impact; addresses critical skills gap in green construction.",
        dateCreated: "2025-02-20T11:30:00Z"
    },
    {
        id: 1003,
        sdl: "5555666677",
        organisationId: 503,
        organisation_Name: "National Manufacturing College",
        organisation_Trade_Name: "NMC",
        contract_Number: "CHI-DG-2025-1003",
        projectId: 2003,
        applicationStatusId: 19,
        projectType: "Bursary",
        project: "Engineering Bursary Programme",
        focusArea: "Manufacturing",
        subCategory: "Mechanical Engineering",
        intervention: "Bursary",
        otherIntervention: null,
        number_Continuing: 10,
        number_New: 15,
        costPerLearner: 65000,
        geC_Continuing: 8,
        geC_New: 12,
        geC_CostPerLearner: 60000,
        gaC_Continuing: 2,
        gaC_New: 3,
        gaC_CostPerLearner: 80000,
        gC_Continuing: 0,
        gC_New: 0,
        gC_CostPerLearner: 0,
        hdi: 72,
        female: 7,
        youth: 25,
        number_Disabled: 0,
        rural: 6,
        province: "KwaZulu-Natal",
        municipality: "eThekwini",
        status: "Allocated to Project Manager",
        sqmrAppIndicator: "No",
        vision2025goal: "Strengthen engineering pipeline",
        leviesuptodate: "Yes",
        previousWSP: "2023/24",
        previousParticipation: "Yes – 2024 DG Cycle",
        approvalStatus: {
            id: 109,
            applicationId: 1003,
            approvalTypeId: 1,
            approvalStatusId: 12,
            comments: "Submitted by online user; awaiting admin review.",
            dateCreated: "2025-04-01T13:10:00Z",
            userId: 205,
            dteUpd: "2025-04-01T13:10:00Z",
            userUpd: 205
        },
        gecStatus: {
            id: 110,
            applicationId: 1003,
            approvalTypeId: 2,
            approvalStatusId: 0,
            comments: "",
            dateCreated: "2025-04-01T13:10:00Z",
            userId: 0,
            dteUpd: null,
            userUpd: 0
        },
        gacStatus: {
            id: 111,
            applicationId: 1003,
            approvalTypeId: 3,
            approvalStatusId: 0,
            comments: "",
            dateCreated: "2025-04-01T13:10:00Z",
            userId: 0,
            dteUpd: null,
            userUpd: 0
        },
        gcStatus: {
            id: 112,
            applicationId: 1003,
            approvalTypeId: 4,
            approvalStatusId: 0,
            comments: "",
            dateCreated: "2025-04-01T13:10:00Z",
            userId: 0,
            dteUpd: null,
            userUpd: 0
        },
        comment: "Priority project – addresses critical engineering shortages.",
        dateCreated: "2025-04-01T13:10:00Z"
    },
    {
        id: 1004,
        sdl: "1122334455",
        organisationId: 504,
        organisation_Name: "Rural Health Training NGO",
        organisation_Trade_Name: "RHT-NGO",
        contract_Number: "CHI-DG-2025-1004",
        projectId: 2004,
        applicationStatusId: 26,
        projectType: "Internship",
        project: "Community Health Worker Internship",
        focusArea: "Healthcare",
        subCategory: "Public Health",
        intervention: "Internship",
        otherIntervention: null,
        number_Continuing: 0,
        number_New: 50,
        costPerLearner: 15000,
        geC_Continuing: 0,
        geC_New: 30,
        geC_CostPerLearner: 13500,
        gaC_Continuing: 0,
        gaC_New: 15,
        gaC_CostPerLearner: 18000,
        gC_Continuing: 0,
        gC_New: 5,
        gC_CostPerLearner: 22000,
        hdi: 48,
        female: 45,
        youth: 42,
        number_Disabled: 2,
        rural: 50,
        province: "Limpopo",
        municipality: "Vhembe",
        status: "Accept With Minor Changes",
        sqmrAppIndicator: "Yes",
        vision2025goal: "Improve rural healthcare access",
        leviesuptodate: "No",
        previousWSP: "2024/25",
        previousParticipation: "Yes – 2023 DG Cycle",
        approvalStatus: {
            id: 113,
            applicationId: 1004,
            approvalTypeId: 1,
            approvalStatusId: 198,
            comments: "Accept With Minor Changes – update risk mitigation plan.",
            dateCreated: "2025-03-25T09:50:22Z",
            userId: 205,
            dteUpd: "2025-03-26T14:20:10Z",
            userUpd: 209
        },
        gecStatus: {
            id: 114,
            applicationId: 1004,
            approvalTypeId: 2,
            approvalStatusId: 86,
            comments: "GEC Committee Review Completed",
            dateCreated: "2025-03-18T16:30:00Z",
            userId: 206,
            dteUpd: "2025-03-18T16:30:00Z",
            userUpd: 206
        },
        gacStatus: {
            id: 115,
            applicationId: 1004,
            approvalTypeId: 3,
            approvalStatusId: 86,
            comments: "GAC Committee Review Completed",
            dateCreated: "2025-03-20T11:15:40Z",
            userId: 207,
            dteUpd: "2025-03-20T11:15:40Z",
            userUpd: 207
        },
        gcStatus: {
            id: 116,
            applicationId: 1004,
            approvalTypeId: 4,
            approvalStatusId: 86,
            comments: "GC Committee Review Completed",
            dateCreated: "2025-03-22T10:45:18Z",
            userId: 208,
            dteUpd: "2025-03-22T10:45:18Z",
            userUpd: 208
        },
        comment: "Exceptional rural & female representation; levy issue to be resolved before signing.",
        dateCreated: "2025-03-10T08:25:00Z"
    }
];

// ==============================================
// 1. MandatoryApplicationDto
// ==============================================
export const mockMandatoryApplications: MandatoryApplicationDto[] = [
    {
        id: 5001,
        grantWindowId: 2025,
        organisationId: 301,
        grantStatusId: 4,
        referenceNo: 20250315001,
        description: "Mandatory Grant Q1 2025 - TechSkills Academy",
        userId: 105,
        dteCreated: "2025-03-15T09:30:00Z",
        captureDate: "2025-03-15T09:30:00Z",
        submissionDte: "2025-03-20T14:45:00Z",
        userSubmitted: 105,
        rsaId: 201,
        rmId: 305,
        submittedPrevious: true,
        usrIdUpd: 105,
        dteUpd: "2025-03-20T14:45:00Z",
        linked: true
    },
    {
        id: 5002,
        grantWindowId: 2025,
        organisationId: 302,
        grantStatusId: 4,
        referenceNo: 20250316002,
        description: "Mandatory Grant Q1 2025 - GreenBuild Institute",
        userId: 106,
        dteCreated: "2025-03-16T10:15:00Z",
        captureDate: "2025-03-16T10:15:00Z",
        submissionDte: "2025-03-21T11:20:00Z",
        userSubmitted: 106,
        rsaId: 202,
        rmId: 306,
        submittedPrevious: false,
        usrIdUpd: 106,
        dteUpd: "2025-03-21T11:20:00Z",
        linked: true
    },
    {
        id: 5003,
        grantWindowId: 2025,
        organisationId: 303,
        grantStatusId: 4,
        referenceNo: 20250317003,
        description: "Mandatory Grant Q1 2025 - EduFuture Consultants",
        userId: 107,
        dteCreated: "2025-03-17T08:45:00Z",
        captureDate: "2025-03-17T08:45:00Z",
        submissionDte: "2025-03-22T09:10:00Z",
        userSubmitted: 107,
        rsaId: 203,
        rmId: 307,
        submittedPrevious: true,
        usrIdUpd: 107,
        dteUpd: "2025-03-22T09:10:00Z",
    },
    {
        id: 5004,
        grantWindowId: 2025,
        organisationId: 304,
        grantStatusId: 4,
        referenceNo: 20250318004,
        description: "Mandatory Grant Q1 2025 - CapeMed Health",
        userId: 108,
        dteCreated: "2025-03-18T13:20:00Z",
        captureDate: "2025-03-18T13:20:00Z",
        submissionDte: "2025-03-23T15:30:00Z",
        userSubmitted: 108,
        rsaId: 204,
        rmId: 308,
        submittedPrevious: true,
        usrIdUpd: 108,
        dteUpd: "2025-03-23T15:30:00Z",
    },
    {
        id: 5005,
        grantWindowId: 2025,
        organisationId: 305,
        grantStatusId: 4,
        referenceNo: 20250319005,
        description: "Mandatory Grant Q1 2025 - TransLogistics SA",
        userId: 109,
        dteCreated: "2025-03-19T11:00:00Z",
        captureDate: "2025-03-19T11:00:00Z",
        submissionDte: "2025-03-24T10:45:00Z",
        userSubmitted: 109,
        rsaId: 205,
        rmId: 309,
        submittedPrevious: false,
        usrIdUpd: 109,
        dteUpd: "2025-03-24T10:45:00Z",
    },
];

// ==============================================
// 2. OrganisationPhysicalAddressDto
// ==============================================
export const mockPhysicalAddresses: OrganisationPhysicalAddressDto[] = [
    {
        id: 701,
        organisationId: 301,
        addressLine1: "123 Greenstone Hill",
        addressLine2: "Block B, Suite 205",
        suburb: "Greenstone",
        area: "East Rand",
        district: "Ekurhuleni",
        municipality: "City of Ekurhuleni",
        province: "Gauteng",
        postcode: "1609",
        dateCreated: "2024-11-10T08:15:00Z",
        userId: "user_105",
    },
    {
        id: 702,
        organisationId: 302,
        addressLine1: "45 Oak Avenue",
        addressLine2: "Unit 3",
        suburb: "Berea",
        area: "Inner City",
        district: "Johannesburg",
        municipality: "City of Johannesburg",
        province: "Gauteng",
        postcode: "2001",
        dateCreated: "2024-10-05T14:30:00Z",
        userId: "user_106",
    },
    {
        id: 703,
        organisationId: 303,
        addressLine1: "78 Long Street",
        addressLine2: null,
        suburb: "City Bowl",
        area: "Central",
        district: "Cape Town",
        municipality: "City of Cape Town",
        province: "Western Cape",
        postcode: "8001",
        dateCreated: "2024-09-12T09:45:00Z",
        userId: "user_107",
    },
    {
        id: 704,
        organisationId: 304,
        addressLine1: "210 Dr Pixley Ka Seme St",
        addressLine2: "Floor 4",
        suburb: "Durban Central",
        area: "Central",
        district: "eThekwini",
        municipality: "eThekwini Metro",
        province: "KwaZulu-Natal",
        postcode: "4001",
        dateCreated: "2024-08-20T11:20:00Z",
        userId: "user_108",
    },
    {
        id: 705,
        organisationId: 305,
        addressLine1: "56 Industrial Road",
        addressLine2: "Warehouse 7",
        suburb: "Isando",
        area: "East Rand",
        district: "Ekurhuleni",
        municipality: "City of Ekurhuleni",
        province: "Gauteng",
        postcode: "1600",
        dateCreated: "2024-12-01T10:10:00Z",
        userId: "user_109",
    },
];

// ==============================================
// 3. OrganisationPostalAddressDto
// ==============================================
export const mockPostalAddresses: OrganisationPostalAddressDto[] = [
    {
        id: 801,
        organisationId: 301,
        sameAsPhysical: true,
        addressLine1: "123 Greenstone Hill",
        addressLine2: "Block B, Suite 205",
        suburb: "Greenstone",
        area: "East Rand",
        district: "Ekurhuleni",
        municipality: "City of Ekurhuleni",
        province: "Gauteng",
        postcode: "1609",
        dateCreated: "2024-11-10T08:15:00Z",
        userId: "user_105",
    },
    {
        id: 802,
        organisationId: 302,
        sameAsPhysical: true,
        addressLine1: "45 Oak Avenue",
        addressLine2: "Unit 3",
        suburb: "Berea",
        area: "Inner City",
        district: "Johannesburg",
        municipality: "City of Johannesburg",
        province: "Gauteng",
        postcode: "2001",
        dateCreated: "2024-10-05T14:30:00Z",
        userId: "user_106",
    },
    {
        id: 803,
        organisationId: 303,
        sameAsPhysical: false,
        addressLine1: "PO Box 12345",
        addressLine2: null,
        suburb: "Cape Town",
        area: null,
        district: null,
        municipality: "City of Cape Town",
        province: "Western Cape",
        postcode: "8000",
        dateCreated: "2024-09-12T09:45:00Z",
        userId: "user_107",
    },
    {
        id: 804,
        organisationId: 304,
        sameAsPhysical: true,
        addressLine1: "210 Dr Pixley Ka Seme St",
        addressLine2: "Floor 4",
        suburb: "Durban Central",
        area: "Central",
        district: "eThekwini",
        municipality: "eThekwini Metro",
        province: "KwaZulu-Natal",
        postcode: "4001",
        dateCreated: "2024-08-20T11:20:00Z",
        userId: "user_108",
    },
    {
        id: 805,
        organisationId: 305,
        sameAsPhysical: false,
        addressLine1: "PO Box 5678",
        addressLine2: null,
        suburb: "Kempton Park",
        area: null,
        district: null,
        municipality: "City of Ekurhuleni",
        province: "Gauteng",
        postcode: "1620",
        dateCreated: "2024-12-01T10:10:00Z",
        userId: "user_109",
    },
];

// ==============================================
// 4. DocumentDto
// ==============================================
export const mockDocuments: DocumentDto[] = [
    {
        id: 901,
        entityId: 5001,
        newFilename: "techskills_mg_q1_2025.pdf",
        filename: "Mandatory_Grant_Application_TechSkills_Q1_2025.pdf",
        lastModifiedDate: "2025-03-20T14:40:00Z",
        size: 2456789,
        type: "application/pdf",
        documentType: "GrantApplication",
        module: "MandatoryGrants",
        dateCreated: "2025-03-20T14:40:00Z",
        userId: "user_105",
    },
    {
        id: 902,
        entityId: 5002,
        newFilename: "greenbuild_mg_q1_2025.pdf",
        filename: "Mandatory_Grant_Application_GreenBuild_Q1_2025.pdf",
        lastModifiedDate: "2025-03-21T11:15:00Z",
        size: 1987654,
        type: "application/pdf",
        documentType: "GrantApplication",
        module: "MandatoryGrants",
        dateCreated: "2025-03-21T11:15:00Z",
        userId: "user_106",
    },
    {
        id: 903,
        entityId: 5003,
        newFilename: "edufuture_mg_q1_2025.pdf",
        filename: "Mandatory_Grant_Application_EduFuture_Q1_2025.pdf",
        lastModifiedDate: "2025-03-22T09:05:00Z",
        size: 3102456,
        type: "application/pdf",
        documentType: "GrantApplication",
        module: "MandatoryGrants",
        dateCreated: "2025-03-22T09:05:00Z",
        userId: "user_107",
    },
    {
        id: 904,
        entityId: 5004,
        newFilename: "capemed_mg_q1_2025.pdf",
        filename: "Mandatory_Grant_Application_CapeMed_Q1_2025.pdf",
        lastModifiedDate: "2025-03-23T15:25:00Z",
        size: 2765432,
        type: "application/pdf",
        documentType: "GrantApplication",
        module: "MandatoryGrants",
        dateCreated: "2025-03-23T15:25:00Z",
        userId: "user_108",
    },
    {
        id: 905,
        entityId: 5005,
        newFilename: "translog_mg_q1_2025.pdf",
        filename: "Mandatory_Grant_Application_TransLogistics_Q1_2025.pdf",
        lastModifiedDate: "2025-03-24T10:40:00Z",
        size: 1845632,
        type: "application/pdf",
        documentType: "GrantApplication",
        module: "MandatoryGrants",
        dateCreated: "2025-03-24T10:40:00Z",
        userId: "user_109",
    },
];

// ==============================================
// 5. MandatoryGrantPaymentDto
// ==============================================
export const mockGrantPayments: MandatoryGrantPaymentDto[] = [
    {
        id: 1101,
        sdlNumber: "1234567890",
        zipfileId: null,
        grantYear: 2025,
        month: 3,
        chietaAccount: "CHI-MG-2025-001",
        chietaCode1: "MG-GT-001",
        orgNameCode: "TECHSKILLS-01",
        bankName: "First National Bank",
        bankAccountNumber: "62514789012",
        code: "051001",
        bankAccountCode: "250610",
        organisationName: "TechSkills Academy (Pty) Ltd",
        sdlCode: "1234567890",
        amount: 245000.0,
        creatorUserId: "user_105",
        deleterUserId: null,
        deletionTime: null,
        isDeleted: false,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: "2025-04-05T10:30:00Z",
    },
    {
        id: 1102,
        sdlNumber: "9876543210",
        zipfileId: null,
        grantYear: 2025,
        month: 3,
        chietaAccount: "CHI-MG-2025-002",
        chietaCode1: "MG-GT-002",
        orgNameCode: "GREENBUILD-01",
        bankName: "Standard Bank",
        bankAccountNumber: "08123456789",
        code: "047101",
        bankAccountCode: "051001",
        organisationName: "GreenBuild Training Institute",
        sdlCode: "9876543210",
        amount: 185000.0,
        creatorUserId: "user_106",
        deleterUserId: null,
        deletionTime: null,
        isDeleted: false,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: "2025-04-06T09:15:00Z",
    },
    {
        id: 1103,
        sdlNumber: "5556667778",
        zipfileId: null,
        grantYear: 2025,
        month: 3,
        chietaAccount: "CHI-MG-2025-003",
        chietaCode1: "MG-GT-003",
        orgNameCode: "EDUFUTURE-01",
        bankName: "Nedbank",
        bankAccountNumber: "12345678901",
        code: "061101",
        bankAccountCode: "198765",
        organisationName: "EduFuture Consultants",
        sdlCode: "5556667778",
        amount: 95000.0,
        creatorUserId: "user_107",
        deleterUserId: null,
        deletionTime: null,
        isDeleted: false,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: "2025-04-07T11:45:00Z",
    },
    {
        id: 1104,
        sdlNumber: "4445556667",
        zipfileId: null,
        grantYear: 2025,
        month: 3,
        chietaAccount: "CHI-MG-2025-004",
        chietaCode1: "MG-GT-004",
        orgNameCode: "CAPEMED-01",
        bankName: "Absa",
        bankAccountNumber: "45098765432",
        code: "083001",
        bankAccountCode: "632005",
        organisationName: "CapeMed Health Services",
        sdlCode: "4445556667",
        amount: 142000.0,
        creatorUserId: "user_108",
        deleterUserId: null,
        deletionTime: null,
        isDeleted: false,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: "2025-04-08T14:20:00Z",
    },
    {
        id: 1105,
        sdlNumber: "3334445556",
        zipfileId: null,
        grantYear: 2025,
        month: 3,
        chietaAccount: "CHI-MG-2025-005",
        chietaCode1: "MG-GT-005",
        orgNameCode: "TRANSLOG-01",
        bankName: "Capitec",
        bankAccountNumber: "100987654321",
        code: "026101",
        bankAccountCode: "470010",
        organisationName: "TransLogistics SA (Pty) Ltd",
        sdlCode: "3334445556",
        amount: 210000.0,
        creatorUserId: "user_109",
        deleterUserId: null,
        deletionTime: null,
        isDeleted: false,
        lastModificationTime: null,
        lastModifierUserId: null,
        creationTime: "2025-04-09T10:10:00Z",
    },
];

// ==============================================
// 6. MandatoryBankingListDto
// ==============================================
export const mockBankingLists: BankDetail[] = [
    {
        id: 101,
        organisationId: 301,
        account_Holder: "TechSkills Academy (Pty) Ltd",
        branch_Code: "250610",
        account_Number: "62514789012",
        branch_Name: "Sandton City",
        bank_Name: "First National Bank",
        accountType: 1,
        userId: 105,
    },
    {
        id: 102,
        organisationId: 302,
        account_Holder: "GreenBuild Training Institute",
        branch_Code: "051001",
        account_Number: "08123456789",
        branch_Name: "Rosebank",
        bank_Name: "Standard Bank",
        accountType: 1,
        userId: 106,
    },
    {
        id: 103,
        organisationId: 303,
        account_Holder: "EduFuture Consultants",
        branch_Code: "198765",
        account_Number: "12345678901",
        branch_Name: "Cape Town Central",
        bank_Name: "Nedbank",
        accountType: 2,
        userId: 107,
    },
    {
        id: 104,
        organisationId: 304,
        account_Holder: "CapeMed Health Services",
        branch_Code: "632005",
        account_Number: "45098765432",
        branch_Name: "Durban Point",
        bank_Name: "Absa",
        accountType: 1,
        userId: 108,
    },
    {
        id: 105,
        organisationId: 305,
        account_Holder: "TransLogistics SA (Pty) Ltd",
        branch_Code: "470010",
        account_Number: "100987654321",
        branch_Name: "Kempton Park",
        bank_Name: "Capitec Bank",
        accountType: 1,
        userId: 109,
    },
];

// ==============================================
// 7. MandatoryGrantBiodataDto
// ==============================================
export const mockBiodataRecords: MandatoryGrantBiodataDto[] = [
    {
        id: 2001,
        applicationId: "5001",
        saIdNumber: "9001015009080",
        passportNumber: null,
        firstname: "Thandi",
        middlename: "Nomsa",
        surname: "Khumalo",
        birthYear: 1990,
        gender: "Female",
        race: "Black",
        disability: "None",
        nationality: "South African",
        province: "Gauteng",
        municipality: "City of Johannesburg",
        highestQualificationType: "Bachelor's Degree",
        employmentStatus: "Employed",
        occupationLevelForEquityReporting: "Professional",
        organisationalStructureFilter: "ICT Department",
        postReference: "ICT-001",
        jobTitle: "Junior Developer",
        ofoOccupationCode: "2523",
        ofoSpecialisation: "Software Development",
        ofoOccupation: "ICT Professionals",
        status: "Active",
        comment: null,
        userId: "user_105",
        dateCreated: "2025-03-18T09:20:00Z",
        usrUpd: "user_105",
        dteUpd: "2025-03-18T09:20:00Z",
    },
    {
        id: 2002,
        applicationId: "5002",
        saIdNumber: "8512150073085",
        passportNumber: null,
        firstname: "Sipho",
        middlename: "David",
        surname: "Molefe",
        birthYear: 1985,
        gender: "Male",
        race: "Black",
        disability: "None",
        nationality: "South African",
        province: "Gauteng",
        municipality: "City of Tshwane",
        highestQualificationType: "National Diploma",
        employmentStatus: "Employed",
        occupationLevelForEquityReporting: "Technician",
        organisationalStructureFilter: "Construction",
        postReference: "CON-012",
        jobTitle: "Green Building Assessor",
        ofoOccupationCode: "3152",
        ofoSpecialisation: "Environmental Assessment",
        ofoOccupation: "Engineering Technicians",
        status: "Active",
        comment: null,
        userId: "user_106",
        dateCreated: "2025-03-19T10:15:00Z",
        usrUpd: "user_106",
        dteUpd: "2025-03-19T10:15:00Z",
    },
    {
        id: 2003,
        applicationId: "5003",
        saIdNumber: null,
        passportNumber: "B98765432",
        firstname: "Lerato",
        middlename: null,
        surname: "Reddy",
        birthYear: 1992,
        gender: "Female",
        race: "Indian",
        disability: "Yes",
        nationality: "South African",
        province: "Western Cape",
        municipality: "City of Cape Town",
        highestQualificationType: "Master's Degree",
        employmentStatus: "Employed",
        occupationLevelForEquityReporting: "Professional",
        organisationalStructureFilter: "Education",
        postReference: "EDU-005",
        jobTitle: "Education Consultant",
        ofoOccupationCode: "2351",
        ofoSpecialisation: "Curriculum Development",
        ofoOccupation: "Education Professionals",
        status: "Active",
        comment: "Hearing impairment - requires subtitles",
        userId: "user_107",
        dateCreated: "2025-03-20T11:30:00Z",
        usrUpd: "user_107",
        dteUpd: "2025-03-20T11:30:00Z",
    },
    {
        id: 2004,
        applicationId: "5004",
        saIdNumber: "8805200092087",
        passportNumber: null,
        firstname: "Nomsa",
        middlename: "Zanele",
        surname: "Buthelezi",
        birthYear: 1988,
        gender: "Female",
        race: "Black",
        disability: "None",
        nationality: "South African",
        province: "KwaZulu-Natal",
        municipality: "eThekwini",
        highestQualificationType: "Bachelor of Nursing",
        employmentStatus: "Employed",
        occupationLevelForEquityReporting: "Professional",
        organisationalStructureFilter: "Healthcare",
        postReference: "HC-022",
        jobTitle: "Community Health Worker",
        ofoOccupationCode: "2221",
        ofoSpecialisation: "Public Health",
        ofoOccupation: "Health Professionals",
        status: "Active",
        comment: null,
        userId: "user_108",
        dateCreated: "2025-03-21T13:45:00Z",
        usrUpd: "user_108",
        dteUpd: "2025-03-21T13:45:00Z",
    },
    {
        id: 2005,
        applicationId: "5005",
        saIdNumber: "9307150108011",
        passportNumber: null,
        firstname: "John",
        middlename: "Mashaba",
        surname: "Mashaba",
        birthYear: 1993,
        gender: "Male",
        race: "Black",
        disability: "None",
        nationality: "South African",
        province: "Gauteng",
        municipality: "City of Ekurhuleni",
        highestQualificationType: "Advanced Certificate",
        employmentStatus: "Employed",
        occupationLevelForEquityReporting: "Associate Professional",
        organisationalStructureFilter: "Logistics",
        postReference: "LOG-033",
        jobTitle: "Freight Coordinator",
        ofoOccupationCode: "3342",
        ofoSpecialisation: "Supply Chain",
        ofoOccupation: "Logistics Professionals",
        status: "Active",
        comment: null,
        userId: "user_109",
        dateCreated: "2025-03-22T08:50:00Z",
        usrUpd: "user_109",
        dteUpd: "2025-03-22T08:50:00Z",
    },
];

export const mockDiscretionaryProjects: DiscretionaryProjectDto[] = [
    {
        id: 1001,
        title: "Green Building Assessor Skills Programme",
        projectType: "Skills Programme",
        focusArea: "Green Economy",
        subCategory: "Construction & Built Environment",
        projectId: 2001,
        applicationId: 1001,
        organisationId: 501,
        projectStatus: "Contract Signed",
        statusDate: "2025-03-21T09:15:12Z",
        endDate: "2026-03-20T00:00:00Z",
        shortName: "GreenBuild-SP",
        fullName: "Green Building Assessor Skills Programme 2025",
        submissionDate: "2025-02-20T11:30:00Z",
        sdlNumber: "1234567890",
        organisationName: "TechSkills Academy (Pty) Ltd",
        sdfId: 301,
        rsaId: 201,
        windowId: 55,
        projectTypeId: 2,
        windowParamId: 101,
        contractStartDate: "2025-03-22T00:00:00Z",
        contractEndDate: "2026-03-21T00:00:00Z",
        isLinked: true
    },
    {
        id: 1002,
        title: "ICT Support Practitioner Learnership",
        projectType: "Learnership",
        focusArea: "Digital Skills",
        subCategory: "Information Technology",
        projectId: 2002,
        applicationId: 1002,
        organisationId: 502,
        projectStatus: "Approved",
        statusDate: "2025-03-12T09:20:15Z",
        endDate: "2026-02-11T00:00:00Z",
        shortName: "ICT-Support-LP",
        fullName: "ICT Support Practitioner Learnership 2025",
        submissionDate: "2025-03-05T08:00:00Z",
        sdlNumber: "9876543210",
        organisationName: "GreenBuild Training Institute",
        sdfId: 302,
        rsaId: 202,
        windowId: 55,
        projectTypeId: 1,
        windowParamId: 102,
        contractStartDate: "2025-03-15T00:00:00Z",
        contractEndDate: "2026-03-14T00:00:00Z",
        isLinked: true
    }
];
export const mockAllDiscretionaryProjects: DiscretionaryProjectDto[] = [
    {
        id: 1001,
        title: "Green Building Assessor Skills Programme",
        projectType: "Skills Programme",
        focusArea: "Green Economy",
        subCategory: "Construction & Built Environment",
        projectId: 2001,
        applicationId: 1001,
        organisationId: 501,
        projectStatus: "Contract Signed",
        statusDate: "2025-03-21T09:15:12Z",
        endDate: "2026-03-20T00:00:00Z",
        shortName: "GreenBuild-SP",
        fullName: "Green Building Assessor Skills Programme 2025",
        submissionDate: "2025-02-20T11:30:00Z",
        sdlNumber: "1234567890",
        organisationName: "TechSkills Academy (Pty) Ltd",
        sdfId: 301,
        rsaId: 201,
        windowId: 55,
        projectTypeId: 2,
        windowParamId: 101,
        contractStartDate: "2025-03-22T00:00:00Z",
        contractEndDate: "2026-03-21T00:00:00Z",
    },
    {
        id: 1002,
        title: "ICT Support Practitioner Learnership",
        projectType: "Learnership",
        focusArea: "Digital Skills",
        subCategory: "Information Technology",
        projectId: 2002,
        applicationId: 1002,
        organisationId: 502,
        projectStatus: "Approved",
        statusDate: "2025-03-12T09:20:15Z",
        endDate: "2026-02-11T00:00:00Z",
        shortName: "ICT-Support-LP",
        fullName: "ICT Support Practitioner Learnership 2025",
        submissionDate: "2025-03-05T08:00:00Z",
        sdlNumber: "9876543210",
        organisationName: "GreenBuild Training Institute",
        sdfId: 302,
        rsaId: 202,
        windowId: 55,
        projectTypeId: 1,
        windowParamId: 102,
        contractStartDate: "2025-03-15T00:00:00Z",
        contractEndDate: "2026-03-14T00:00:00Z",
    },
    {
        id: 1003,
        title: "Digital Literacy for Rural Women",
        projectType: "Skills Programme",
        focusArea: "Digital Inclusion",
        subCategory: "Community Development",
        projectId: 2003,
        applicationId: 1003,
        organisationId: 503,
        projectStatus: "Funding Approved",
        statusDate: "2025-02-28T14:30:00Z",
        endDate: "2025-11-27T00:00:00Z",
        shortName: "Rural-Digital-SP",
        fullName: "Digital Literacy for Rural Women 2025",
        submissionDate: "2025-02-10T10:15:00Z",
        sdlNumber: "5556667778",
        organisationName: "EduFuture Consultants",
        sdfId: 303,
        rsaId: 203,
        windowId: 55,
        projectTypeId: 2,
        windowParamId: 103,
        contractStartDate: "2025-03-01T00:00:00Z",
        contractEndDate: "2025-12-01T00:00:00Z",
    },
    {
        id: 1004,
        title: "Community Health Worker Training",
        projectType: "Learnership",
        focusArea: "Healthcare",
        subCategory: "Public Health",
        projectId: 2004,
        applicationId: 1004,
        organisationId: 504,
        projectStatus: "GEC Review Completed",
        statusDate: "2025-01-20T11:25:30Z",
        endDate: "2025-12-19T00:00:00Z",
        shortName: "CHW-LP",
        fullName: "Community Health Worker Learnership 2025",
        submissionDate: "2025-01-05T09:00:00Z",
        sdlNumber: "4445556667",
        organisationName: "CapeMed Health Services",
        sdfId: 304,
        rsaId: 204,
        windowId: 55,
        projectTypeId: 1,
        windowParamId: 104,
        contractStartDate: "2025-02-01T00:00:00Z",
        contractEndDate: "2026-01-31T00:00:00Z",
    },
    {
        id: 1005,
        title: "Green Logistics Coordinator Programme",
        projectType: "Skills Programme",
        focusArea: "Green Economy",
        subCategory: "Logistics & Supply Chain",
        projectId: 2005,
        applicationId: 1005,
        organisationId: 505,
        projectStatus: "Submitted",
        statusDate: "2025-03-24T10:45:00Z",
        endDate: "2026-03-23T00:00:00Z",
        shortName: "GreenLog-SP",
        fullName: "Green Logistics Coordinator Skills Programme 2025",
        submissionDate: "2025-03-19T11:00:00Z",
        sdlNumber: "3334445556",
        organisationName: "TransLogistics SA (Pty) Ltd",
        sdfId: 305,
        rsaId: 205,
        windowId: 55,
        projectTypeId: 2,
        windowParamId: 105,
        contractStartDate: "2025-04-01T00:00:00Z",
        contractEndDate: "2026-03-31T00:00:00Z",
    },
];