import { DiscretionaryProjectDetailsApproval } from "../models/DiscretionaryDto";
import { OrganisationDto } from "../models/organizationDto";

export const org_data: OrganisationDto[] = [
    {
        "sdlNo": "SDL1234567890",
        "setaId": 101,
        "seta": "BankSETA",
        "sicCode": "6411",
        "organisationRegistrationNumber": "1995/012345/07",
        "organisationName": "FinTrust Bank Ltd",
        "organisationTradingName": "FinTrust",
        "organisationFaxNumber": "+27-11-123-4567",
        "organisationContactName": "Jane Smith",
        "organisationContactEmailAddress": "jane.smith@fintrust.co.za",
        "organisationContactPhoneNumber": "+27-11-987-6543",
        "organisationContactCellNumber": "+27-82-123-4567",
        "companySize": "Large",
        "numberOfEmployees": 1250,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Retail and Commercial Banking",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 4,
        "dateBusinessCommenced": "1995-03-15T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "Banking Association of South Africa",
        "ceoName": "Michael",
        "ceoSurname": "van der Merwe",
        "ceoEmail": "m.vandermerwe@fintrust.co.za",
        "ceoRaceId": "2",
        "ceoGenderId": "M",
        "seniorRepName": "Lerato",
        "seniorRepSurname": "Mokoena",
        "seniorRepEmail": "l.mokoena@fintrust.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "F",
        "id": 1
    },
    {
        "sdlNo": "SDL9876543210",
        "setaId": 205,
        "seta": "MerSETA",
        "sicCode": "4510",
        "organisationRegistrationNumber": "2008/987654/23",
        "organisationName": "AutoDrive Motors (Pty) Ltd",
        "organisationTradingName": "AutoDrive",
        "organisationFaxNumber": "+27-21-456-7890",
        "organisationContactName": null,
        "organisationContactEmailAddress": "info@autodrive.co.za",
        "organisationContactPhoneNumber": "+27-21-123-4567",
        "organisationContactCellNumber": "+27-83-987-6543",
        "companySize": "Medium",
        "numberOfEmployees": 85,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Vehicle Retail and Servicing",
        "parentSdlNumber": "SDL1234567890",
        "bbbeeStatus": "Non-Compliant",
        "bbbeeLevel": 0,
        "dateBusinessCommenced": "2008-11-02T00:00:00Z",
        "status": "Active",
        "exemptionCode": 5,
        "chamber": "National Automobile Dealers Association",
        "ceoName": "David",
        "ceoSurname": "Naidoo",
        "ceoEmail": "d.naidoo@autodrive.co.za",
        "ceoRaceId": "3",
        "ceoGenderId": "M",
        "seniorRepName": "Thandi",
        "seniorRepSurname": "Khumalo",
        "seniorRepEmail": "t.khumalo@autodrive.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "F",
        "id": 2
    },
    {
        "sdlNo": "SDL5556667778",
        "setaId": 302,
        "seta": "Services SETA",
        "sicCode": "7910",
        "organisationRegistrationNumber": "2015/445566/07",
        "organisationName": "Elite Hospitality Group",
        "organisationTradingName": "EliteStay",
        "organisationFaxNumber": "+27-31-222-3333",
        "organisationContactName": "Sarah Johnson",
        "organisationContactEmailAddress": "sarah@elitestay.co.za",
        "organisationContactPhoneNumber": "+27-31-444-5555",
        "organisationContactCellNumber": "+27-84-111-2222",
        "companySize": "Small",
        "numberOfEmployees": 42,
        "typeOfEntity": "CC (Close Corporation)",
        "coreBusiness": "Hotel and Accommodation Services",
        "parentSdlNumber": null,
        "bbbeeStatus": "Exempt",
        "bbbeeLevel": 0,
        "dateBusinessCommenced": "2015-07-20T00:00:00Z",
        "status": "Active",
        "exemptionCode": 2,
        "chamber": "South African Tourism",
        "ceoName": "Anita",
        "ceoSurname": "Reddy",
        "ceoEmail": "a.reddy@elitestay.co.za",
        "ceoRaceId": "4",
        "ceoGenderId": "F",
        "seniorRepName": "James",
        "seniorRepSurname": "Petersen",
        "seniorRepEmail": "j.petersen@elitestay.co.za",
        "seniorRepRaceId": "5",
        "seniorRepGenderId": "M",
        "id": 3
    },
    {
        "sdlNo": "SDL8889990001",
        "setaId": 107,
        "seta": "EWSETA",
        "sicCode": "3510",
        "organisationRegistrationNumber": "2010/778899/07",
        "organisationName": "GreenPower Solutions (Pty) Ltd",
        "organisationTradingName": "GreenPower",
        "organisationFaxNumber": "+27-12-666-7777",
        "organisationContactName": "Mark Williams",
        "organisationContactEmailAddress": "contact@greenpower.co.za",
        "organisationContactPhoneNumber": "+27-12-888-9999",
        "organisationContactCellNumber": "+27-81-333-4444",
        "companySize": "Medium",
        "numberOfEmployees": 112,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Renewable Energy Installation",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 5,
        "dateBusinessCommenced": "2010-09-10T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "South African Renewable Energy Council",
        "ceoName": "Sipho",
        "ceoSurname": "Dlamini",
        "ceoEmail": "s.dlamini@greenpower.co.za",
        "ceoRaceId": "1",
        "ceoGenderId": "M",
        "seniorRepName": "Nomsa",
        "seniorRepSurname": "Zulu",
        "seniorRepEmail": "n.zulu@greenpower.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "F",
        "id": 4
    },
    {
        "sdlNo": "SDL2223334445",
        "setaId": 401,
        "seta": "AGRISETA",
        "sicCode": "0111",
        "organisationRegistrationNumber": "1998/556677/23",
        "organisationName": "Golden Fields Farming Co",
        "organisationTradingName": "Golden Fields",
        "organisationFaxNumber": "+27-51-111-2222",
        "organisationContactName": null,
        "organisationContactEmailAddress": "info@goldenfields.co.za",
        "organisationContactPhoneNumber": "+27-51-333-4444",
        "organisationContactCellNumber": "+27-82-555-6666",
        "companySize": "Large",
        "numberOfEmployees": 320,
        "typeOfEntity": "Cooperative",
        "coreBusiness": "Maize and Wheat Farming",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 3,
        "dateBusinessCommenced": "1998-01-05T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "Agricultural Union of South Africa",
        "ceoName": "Kagiso",
        "ceoSurname": "Molefe",
        "ceoEmail": "k.molefe@goldenfields.co.za",
        "ceoRaceId": "1",
        "ceoGenderId": "M",
        "seniorRepName": "Elsabe",
        "seniorRepSurname": "Botha",
        "seniorRepEmail": "e.botha@goldenfields.co.za",
        "seniorRepRaceId": "2",
        "seniorRepGenderId": "F",
        "id": 5
    },
    {
        "sdlNo": "SDL6667778889",
        "setaId": 209,
        "seta": "CETA",
        "sicCode": "4100",
        "organisationRegistrationNumber": "2012/112233/07",
        "organisationName": "BuildRight Construction (Pty) Ltd",
        "organisationTradingName": "BuildRight",
        "organisationFaxNumber": "+27-11-777-8888",
        "organisationContactName": "Tanya Moodley",
        "organisationContactEmailAddress": "tanya@buildright.co.za",
        "organisationContactPhoneNumber": "+27-11-999-0000",
        "organisationContactCellNumber": "+27-83-777-8888",
        "companySize": "Medium",
        "numberOfEmployees": 95,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Residential Construction",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 6,
        "dateBusinessCommenced": "2012-05-17T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "Master Builders South Africa",
        "ceoName": "Raj",
        "ceoSurname": "Gandhi",
        "ceoEmail": "r.gandhi@buildright.co.za",
        "ceoRaceId": "4",
        "ceoGenderId": "M",
        "seniorRepName": "Zanele",
        "seniorRepSurname": "Khuzwayo",
        "seniorRepEmail": "z.khuzwayo@buildright.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "F",
        "id": 6
    },
    {
        "sdlNo": "SDL3334445556",
        "setaId": 503,
        "seta": "TETA",
        "sicCode": "4920",
        "organisationRegistrationNumber": "2005/334455/07",
        "organisationName": "TransLogistics SA (Pty) Ltd",
        "organisationTradingName": "TransLog",
        "organisationFaxNumber": "+27-10-222-3333",
        "organisationContactName": null,
        "organisationContactEmailAddress": "dispatch@translog.co.za",
        "organisationContactPhoneNumber": "+27-10-444-5555",
        "organisationContactCellNumber": "+27-81-222-3333",
        "companySize": "Large",
        "numberOfEmployees": 410,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Freight and Logistics",
        "parentSdlNumber": "SDL2223334445",
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 2,
        "dateBusinessCommenced": "2005-12-01T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "South African Freight Forwarders Association",
        "ceoName": "John",
        "ceoSurname": "Mashaba",
        "ceoEmail": "j.mashaba@translog.co.za",
        "ceoRaceId": "1",
        "ceoGenderId": "M",
        "seniorRepName": "Amina",
        "seniorRepSurname": "Hassan",
        "seniorRepEmail": "a.hassan@translog.co.za",
        "seniorRepRaceId": "3",
        "seniorRepGenderId": "F",
        "id": 7
    },
    {
        "sdlNo": "SDL9990001112",
        "setaId": 110,
        "seta": "FASSET",
        "sicCode": "6619",
        "organisationRegistrationNumber": "2017/990011/07",
        "organisationName": "EduFuture Consultants",
        "organisationTradingName": "EduFuture",
        "organisationFaxNumber": "+27-15-666-7777",
        "organisationContactName": "Dr. Linda Pretorius",
        "organisationContactEmailAddress": "linda@edufuture.co.za",
        "organisationContactPhoneNumber": "+27-15-888-9999",
        "organisationContactCellNumber": "+27-82-999-0000",
        "companySize": "Small",
        "numberOfEmployees": 18,
        "typeOfEntity": "Sole Proprietor",
        "coreBusiness": "Educational Training and Development",
        "parentSdlNumber": null,
        "bbbeeStatus": "Exempt",
        "bbbeeLevel": 0,
        "dateBusinessCommenced": "2017-02-28T00:00:00Z",
        "status": "Active",
        "exemptionCode": 3,
        "chamber": "South African Institute for Education",
        "ceoName": "Linda",
        "ceoSurname": "Pretorius",
        "ceoEmail": "l.pretorius@edufuture.co.za",
        "ceoRaceId": "2",
        "ceoGenderId": "F",
        "seniorRepName": "Linda",
        "seniorRepSurname": "Pretorius",
        "seniorRepEmail": "l.pretorius@edufuture.co.za",
        "seniorRepRaceId": "2",
        "seniorRepGenderId": "F",
        "id": 8
    },
    {
        "sdlNo": "SDL4445556667",
        "setaId": 600,
        "seta": "W&RSETA",
        "sicCode": "8610",
        "organisationRegistrationNumber": "2009/445566/07",
        "organisationName": "CapeMed Health Services",
        "organisationTradingName": "CapeMed",
        "organisationFaxNumber": "+27-21-121-2121",
        "organisationContactName": "Dr. Thabo Moloi",
        "organisationContactEmailAddress": "info@capemed.co.za",
        "organisationContactPhoneNumber": "+27-21-343-4343",
        "organisationContactCellNumber": "+27-83-565-6565",
        "companySize": "Medium",
        "numberOfEmployees": 76,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Private Healthcare Clinics",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 4,
        "dateBusinessCommenced": "2009-08-14T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "Private Healthcare Providers Association",
        "ceoName": "Thabo",
        "ceoSurname": "Moloi",
        "ceoEmail": "t.moloi@capemed.co.za",
        "ceoRaceId": "1",
        "ceoGenderId": "M",
        "seniorRepName": "Nandi",
        "seniorRepSurname": "Buthelezi",
        "seniorRepEmail": "n.buthelezi@capemed.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "F",
        "id": 9
    },
    {
        "sdlNo": "SDL7778889990",
        "setaId": 701,
        "seta": "MICT SETA",
        "sicCode": "6190",
        "organisationRegistrationNumber": "2020/778899/07",
        "organisationName": "TechNova Solutions (Pty) Ltd",
        "organisationTradingName": "TechNova",
        "organisationFaxNumber": "+27-11-878-7878",
        "organisationContactName": null,
        "organisationContactEmailAddress": "hello@technova.co.za",
        "organisationContactPhoneNumber": "+27-11-989-8989",
        "organisationContactCellNumber": "+27-81-112-2112",
        "companySize": "Small",
        "numberOfEmployees": 28,
        "typeOfEntity": "Private Company",
        "coreBusiness": "Software Development and IT Consulting",
        "parentSdlNumber": null,
        "bbbeeStatus": "Compliant",
        "bbbeeLevel": 5,
        "dateBusinessCommenced": "2020-10-01T00:00:00Z",
        "status": "Active",
        "exemptionCode": 0,
        "chamber": "Institute of Information Technology Professionals SA",
        "ceoName": "Chen",
        "ceoSurname": "Wang",
        "ceoEmail": "c.wang@technova.co.za",
        "ceoRaceId": "4",
        "ceoGenderId": "M",
        "seniorRepName": "Ayanda",
        "seniorRepSurname": "Nkosi",
        "seniorRepEmail": "a.nkosi@technova.co.za",
        "seniorRepRaceId": "1",
        "seniorRepGenderId": "M",
        "id": 10
    }
];

export const mockDiscretionaryProjectDetailsApprovals: DiscretionaryProjectDetailsApproval[] = [
    {
        id: 1,
        projectId: 101,
        projectTypeId: 2,
        applicationStatusId: 3,
        submittedBy: "john.doe@chieta.org",
        submissionDte: "2024-11-15T10:30:00Z",
        currentApprover: "Jane Smith",
        contractNumber: "CT-2024-DISC-001",
        reason: "Skills development for youth in rural areas",
        approvalStatus: "Pending",
        focusAreaId: 5,
        subCategoryId: 12,
        interventionId: 7,
        otherIntervention: null,
        focusCritEvalId: 4,
        numberContinuing: 30,
        numberNew: 70,
        costPerLearner: 4500.0,
        gecNew: 20,
        gecContinuing: 10,
        gecCostPerLearner: 5000.0,
        gacNew: 15,
        gacContinuing: 8,
        gacCostPerLearner: 4800.0,
        gcNew: 35,
        gcContinuing: 12,
        gcCostPerLearner: 4600.0,
        hdi: 0.65,
        female: 42,
        youth: 58,
        numberDisabled: 5,
        rural: 25,
        province: "Gauteng",
        municipality: "City of Johannesburg",
        district: "Region F",
        vision2025goal: "Increase youth employability through accredited training",
        sqmrAppIndicator: true,
        leviesUptodate: true,
        previousWsp: "2023-WSP-CHIETA-889",
        previousParticipation: "Yes – 2022 Discretionary Grant",
        dateCreated: "2024-11-15T09:15:00Z",
        userId: "user_789",
        usrUpd: "admin_user",
        dteUpd: "2024-11-16T14:20:00Z",
        comments: "Strong alignment with rural development goals.",
        companyTypeId: 1,
        companyComplianceId: 3,
        discLearnerTypeId: 2,
        hiStoricalPerfomanceId: 5,
        newCompany: false,
        linkToSsp: "https://ssp.chieta.org.za/project/101"
    },
    {
        id: 2,
        projectId: 102,
        projectTypeId: 1,
        applicationStatusId: 2,
        submittedBy: "sarah.lee@skillsdev.co.za",
        submissionDte: "2024-12-01T08:45:00Z",
        currentApprover: null,
        contractNumber: null,
        reason: "Upskilling employees in green energy sector",
        approvalStatus: "Submitted",
        focusAreaId: 3,
        subCategoryId: 8,
        interventionId: 9,
        otherIntervention: "Renewable energy technician training",
        focusCritEvalId: 2,
        numberContinuing: 0,
        numberNew: 50,
        costPerLearner: 6200.0,
        gecNew: 50,
        gecContinuing: 0,
        gecCostPerLearner: 6200.0,
        gacNew: 45,
        gacContinuing: 0,
        gacCostPerLearner: 6100.0,
        gcNew: 50,
        gcContinuing: 0,
        gcCostPerLearner: 6150.0,
        hdi: 0.72,
        female: 30,
        youth: 40,
        numberDisabled: 2,
        rural: 0,
        province: "Western Cape",
        municipality: "City of Cape Town",
        district: "Southern Suburbs",
        vision2025goal: "Support just energy transition",
        sqmrAppIndicator: true,
        leviesUptodate: true,
        previousWsp: null,
        previousParticipation: "No",
        dateCreated: "2024-12-01T08:30:00Z",
        userId: "user_456",
        usrUpd: null,
        dteUpd: null,
        comments: null,
        companyTypeId: 2,
        companyComplianceId: 1,
        discLearnerTypeId: 1,
        hiStoricalPerfomanceId: 4,
        newCompany: true,
        linkToSsp: null
    },
    {
        id: 3,
        projectId: 103,
        projectTypeId: 3,
        applicationStatusId: 4,
        submittedBy: "michael.ngo@edutrain.org",
        submissionDte: "2024-10-20T14:20:00Z",
        currentApprover: "David van der Merwe",
        contractNumber: "CT-2024-DISC-003",
        reason: "Digital literacy for women in informal settlements",
        approvalStatus: "Approved",
        focusAreaId: 2,
        subCategoryId: 5,
        interventionId: 4,
        otherIntervention: null,
        focusCritEvalId: 3,
        numberContinuing: 20,
        numberNew: 80,
        costPerLearner: 3200.0,
        gecNew: 60,
        gecContinuing: 15,
        gecCostPerLearner: 3400.0,
        gacNew: 55,
        gacContinuing: 10,
        gacCostPerLearner: 3300.0,
        gcNew: 70,
        gcContinuing: 18,
        gcCostPerLearner: 3250.0,
        hdi: 0.58,
        female: 75,
        youth: 65,
        numberDisabled: 8,
        rural: 12,
        province: "KwaZulu-Natal",
        municipality: "eThekwini",
        district: "Durban Central",
        vision2025goal: "Bridge gender digital divide",
        sqmrAppIndicator: true,
        leviesUptodate: false,
        previousWsp: "2023-WSP-CHIETA-455",
        previousParticipation: "Yes – 2021",
        dateCreated: "2024-10-20T13:00:00Z",
        userId: "user_222",
        usrUpd: "approver_01",
        dteUpd: "2024-10-25T09:10:00Z",
        comments: "Approved with condition: submit quarterly impact reports.",
        companyTypeId: 3,
        companyComplianceId: 2,
        discLearnerTypeId: 3,
        hiStoricalPerfomanceId: 6,
        newCompany: false,
        linkToSsp: "https://ssp.chieta.org.za/project/103"
    },
    {
        id: 4,
        projectId: 104,
        projectTypeId: 2,
        applicationStatusId: 1,
        submittedBy: "admin@techfuture.co.za",
        submissionDte: "2025-01-05T11:15:00Z",
        currentApprover: null,
        contractNumber: null,
        reason: "AI and data science upskilling for SMEs",
        approvalStatus: "Draft",
        focusAreaId: 6,
        subCategoryId: 15,
        interventionId: 11,
        otherIntervention: "Machine learning certification",
        focusCritEvalId: 5,
        numberContinuing: 10,
        numberNew: 40,
        costPerLearner: 8900.0,
        gecNew: 30,
        gecContinuing: 5,
        gecCostPerLearner: 9000.0,
        gacNew: 28,
        gacContinuing: 4,
        gacCostPerLearner: 8800.0,
        gcNew: 35,
        gcContinuing: 6,
        gcCostPerLearner: 8950.0,
        hdi: 0.81,
        female: 25,
        youth: 70,
        numberDisabled: 0,
        rural: 5,
        province: "Gauteng",
        municipality: "City of Tshwane",
        district: "Pretoria East",
        vision2025goal: "Build future-ready tech talent",
        sqmrAppIndicator: null,
        leviesUptodate: true,
        previousWsp: null,
        previousParticipation: "No",
        dateCreated: "2025-01-05T10:00:00Z",
        userId: "user_999",
        usrUpd: null,
        dteUpd: null,
        comments: null,
        companyTypeId: 1,
        companyComplianceId: 1,
        discLearnerTypeId: 1,
        hiStoricalPerfomanceId: 2,
        newCompany: true,
        linkToSsp: null
    },
    {
        id: 5,
        projectId: 105,
        projectTypeId: 4,
        applicationStatusId: 3,
        submittedBy: "nomsa.khumalo@agripro.co.za",
        submissionDte: "2024-12-18T09:30:00Z",
        currentApprover: "Thandi Naidoo",
        contractNumber: null,
        reason: "Agricultural mechanization training for smallholders",
        approvalStatus: "Pending",
        focusAreaId: 1,
        subCategoryId: 3,
        interventionId: 2,
        otherIntervention: null,
        focusCritEvalId: 1,
        numberContinuing: 25,
        numberNew: 45,
        costPerLearner: 5400.0,
        gecNew: 35,
        gecContinuing: 20,
        gecCostPerLearner: 5500.0,
        gacNew: 30,
        gacContinuing: 18,
        gacCostPerLearner: 5300.0,
        gcNew: 40,
        gcContinuing: 22,
        gcCostPerLearner: 5350.0,
        hdi: 0.52,
        female: 50,
        youth: 30,
        numberDisabled: 3,
        rural: 40,
        province: "Limpopo",
        municipality: "Vhembe",
        district: "Thohoyandou",
        vision2025goal: "Enhance food security through modern farming",
        sqmrAppIndicator: true,
        leviesUptodate: true,
        previousWsp: "2023-WSP-CHIETA-771",
        previousParticipation: "Yes – 2023",
        dateCreated: "2024-12-18T08:45:00Z",
        userId: "user_555",
        usrUpd: null,
        dteUpd: null,
        comments: "Awaiting budget confirmation from finance.",
        companyTypeId: 4,
        companyComplianceId: 3,
        discLearnerTypeId: 4,
        hiStoricalPerfomanceId: 7,
        newCompany: false,
        linkToSsp: null
    },
    {
        id: 6,
        projectId: 106,
        projectTypeId: 2,
        applicationStatusId: 5,
        submittedBy: "robert.mokoena@buildskills.co.za",
        submissionDte: "2024-09-10T13:45:00Z",
        currentApprover: "Sipho Dlamini",
        contractNumber: "CT-2024-DISC-006",
        reason: "Construction safety and scaffolding certification",
        approvalStatus: "Rejected",
        focusAreaId: 4,
        subCategoryId: 10,
        interventionId: 6,
        otherIntervention: null,
        focusCritEvalId: 6,
        numberContinuing: 15,
        numberNew: 35,
        costPerLearner: 4100.0,
        gecNew: 25,
        gecContinuing: 10,
        gecCostPerLearner: 4200.0,
        gacNew: 20,
        gacContinuing: 8,
        gacCostPerLearner: 4000.0,
        gcNew: 30,
        gcContinuing: 12,
        gcCostPerLearner: 4050.0,
        hdi: 0.60,
        female: 10,
        youth: 50,
        numberDisabled: 1,
        rural: 20,
        province: "Eastern Cape",
        municipality: "Buffalo City",
        district: "East London",
        vision2025goal: "Improve workplace safety in construction",
        sqmrAppIndicator: false,
        leviesUptodate: false,
        previousWsp: "2022-WSP-CHIETA-333",
        previousParticipation: "Yes – 2022",
        dateCreated: "2024-09-10T12:30:00Z",
        userId: "user_333",
        usrUpd: "reviewer_02",
        dteUpd: "2024-09-20T16:00:00Z",
        comments: "Rejected: levy payments overdue and incomplete WSP submission.",
        companyTypeId: 2,
        companyComplianceId: 5,
        discLearnerTypeId: 2,
        hiStoricalPerfomanceId: 3,
        newCompany: false,
        linkToSsp: null
    },
    {
        id: 7,
        projectId: 107,
        projectTypeId: 1,
        applicationStatusId: 3,
        submittedBy: "lerato.maleka@healthfirst.org",
        submissionDte: "2025-01-10T10:00:00Z",
        currentApprover: "Dr. Nomvula Maseko",
        contractNumber: null,
        reason: "Community health worker training in TB and HIV",
        approvalStatus: "Pending",
        focusAreaId: 7,
        subCategoryId: 18,
        interventionId: 13,
        otherIntervention: "Mobile clinic support",
        focusCritEvalId: 7,
        numberContinuing: 40,
        numberNew: 60,
        costPerLearner: 3800.0,
        gecNew: 50,
        gecContinuing: 30,
        gecCostPerLearner: 3900.0,
        gacNew: 45,
        gacContinuing: 25,
        gacCostPerLearner: 3750.0,
        gcNew: 55,
        gcContinuing: 35,
        gcCostPerLearner: 3800.0,
        hdi: 0.55,
        female: 85,
        youth: 45,
        numberDisabled: 4,
        rural: 50,
        province: "Mpumalanga",
        municipality: "Ehlanzeni",
        district: "Nelspruit",
        vision2025goal: "Strengthen primary healthcare access",
        sqmrAppIndicator: true,
        leviesUptodate: true,
        previousWsp: "2023-WSP-CHIETA-999",
        previousParticipation: "Yes – 2020, 2022",
        dateCreated: "2025-01-10T09:15:00Z",
        userId: "user_777",
        usrUpd: null,
        dteUpd: null,
        comments: "High priority due to disease burden in region.",
        companyTypeId: 5,
        companyComplianceId: 2,
        discLearnerTypeId: 5,
        hiStoricalPerfomanceId: 8,
        newCompany: false,
        linkToSsp: null
    },
    {
        id: 8,
        projectId: 108,
        projectTypeId: 3,
        applicationStatusId: 4,
        submittedBy: "james.petersen@techacademy.co.za",
        submissionDte: "2024-11-30T15:20:00Z",
        currentApprover: "Anita Reddy",
        contractNumber: "CT-2024-DISC-008",
        reason: "Coding bootcamp for unemployed graduates",
        approvalStatus: "Approved",
        focusAreaId: 6,
        subCategoryId: 14,
        interventionId: 10,
        otherIntervention: null,
        focusCritEvalId: 5,
        numberContinuing: 0,
        numberNew: 100,
        costPerLearner: 7500.0,
        gecNew: 80,
        gecContinuing: 0,
        gecCostPerLearner: 7600.0,
        gacNew: 70,
        gacContinuing: 0,
        gacCostPerLearner: 7400.0,
        gcNew: 90,
        gcContinuing: 0,
        gcCostPerLearner: 7500.0,
        hdi: 0.78,
        female: 40,
        youth: 95,
        numberDisabled: 5,
        rural: 15,
        province: "Gauteng",
        municipality: "Ekurhuleni",
        district: "East Rand",
        vision2025goal: "Reduce graduate unemployment through tech skills",
        sqmrAppIndicator: true,
        leviesUptodate: true,
        previousWsp: "2023-WSP-CHIETA-112",
        previousParticipation: "Yes – 2023",
        dateCreated: "2024-11-30T14:00:00Z",
        userId: "user_888",
        usrUpd: "approver_03",
        dteUpd: "2024-12-05T11:30:00Z",
        comments: "Approved. Partner with 3 local universities for placement.",
        companyTypeId: 1,
        companyComplianceId: 1,
        discLearnerTypeId: 1,
        hiStoricalPerfomanceId: 9,
        newCompany: false,
        linkToSsp: "https://ssp.chieta.org.za/project/108"
    },
    {
        id: 9,
        projectId: 109,
        projectTypeId: 2,
        applicationStatusId: 2,
        submittedBy: "thabo.molefe@agritech.co.za",
        submissionDte: "2025-01-15T09:10:00Z",
        currentApprover: null,
        contractNumber: null,
        reason: "Drone operation and precision agriculture",
        approvalStatus: "Submitted",
        focusAreaId: 1,
        subCategoryId: 4,
        interventionId: 3,
        otherIntervention: "Drone pilot certification",
        focusCritEvalId: 1,
        numberContinuing: 5,
        numberNew: 25,
        costPerLearner: 12000.0,
        gecNew: 20,
        gecContinuing: 3,
        gecCostPerLearner: 12500.0,
        gacNew: 18,
        gacContinuing: 2,
        gacCostPerLearner: 11800.0,
        gcNew: 22,
        gcContinuing: 4,
        gcCostPerLearner: 12000.0,
        hdi: 0.62,
        female: 20,
        youth: 60,
        numberDisabled: 0,
        rural: 22,
        province: "North West",
        municipality: "Ngaka Modiri Molema",
        district: "Mahikeng",
        vision2025goal: "Modernize small-scale farming with technology",
        sqmrAppIndicator: true,
        leviesUptodate: true,
        previousWsp: null,
        previousParticipation: "No",
        dateCreated: "2025-01-15T08:30:00Z",
        userId: "user_123",
        usrUpd: null,
        dteUpd: null,
        comments: null,
        companyTypeId: 2,
        companyComplianceId: 2,
        discLearnerTypeId: 2,
        hiStoricalPerfomanceId: 1,
        newCompany: true,
        linkToSsp: null
    },
    {
        id: 10,
        projectId: 110,
        projectTypeId: 4,
        applicationStatusId: 3,
        submittedBy: "zanele.khumalo@textileskills.co.za",
        submissionDte: "2024-12-20T12:00:00Z",
        currentApprover: "Raj Gandhi",
        contractNumber: null,
        reason: "Apparel manufacturing and design for women cooperatives",
        approvalStatus: "Pending",
        focusAreaId: 8,
        subCategoryId: 20,
        interventionId: 15,
        otherIntervention: "Sustainable fabric sourcing",
        focusCritEvalId: 8,
        numberContinuing: 30,
        numberNew: 70,
        costPerLearner: 4200.0,
        gecNew: 60,
        gecContinuing: 25,
        gecCostPerLearner: 4300.0,
        gacNew: 55,
        gacContinuing: 20,
        gacCostPerLearner: 4100.0,
        gcNew: 65,
        gcContinuing: 28,
        gcCostPerLearner: 4200.0,
        hdi: 0.59,
        female: 100,
        youth: 55,
        numberDisabled: 6,
        rural: 35,
        province: "KwaZulu-Natal",
        municipality: "uMgungundlovu",
        district: "Pietermaritzburg",
        vision2025goal: "Empower women through sustainable fashion",
        sqmrAppIndicator: true,
        leviesUptodate: true,
        previousWsp: "2023-WSP-CHIETA-555",
        previousParticipation: "Yes – 2021, 2023",
        dateCreated: "2024-12-20T11:15:00Z",
        userId: "user_444",
        usrUpd: null,
        dteUpd: null,
        comments: "Awaiting site verification report.",
        companyTypeId: 3,
        companyComplianceId: 3,
        discLearnerTypeId: 6,
        hiStoricalPerfomanceId: 10,
        newCompany: false,
        linkToSsp: null
    }
];