import colors from "@/config/colors";
import { StyleSheet } from "react-native";
import { moderateScale, scale, verticalScale } from "@/utils/responsive";

export const landing_styles = StyleSheet.create({
    container: {
        flex: 1,
        paddingTop: scale(12),
        paddingHorizontal: scale(16),
    },

    logo: {
        width: scale(160),
        height: scale(160),
        alignSelf: "center",
        marginVertical: scale(24),
    },

    title: {
        fontSize: moderateScale(28),
        fontWeight: "700",
        color: colors.primary[700] || "#4c1d95",
        textAlign: "center",
        marginBottom: 8,
    },

    subtitle: {
        fontSize: moderateScale(16),
        color: "#6b7280",
        textAlign: "center",
        marginBottom: scale(32),
    },

    grid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        gap: scale(12),
    },

    card: {
        width: "47%",
        backgroundColor: "white",
        borderRadius: 16,
        padding: scale(16),
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#e5e7eb",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 6,
        elevation: 3,
    },
    cardDisabled: {
        opacity: 0.6,
    },

    icon: {
        marginBottom: scale(10),
    },

    cardTitle: {
        fontSize: moderateScale(17),
        fontWeight: "600",
        color: "#1f2937",
        marginBottom: 8,
    },
    cardTitleDisabled: {
        color: "#6b7280",
    },

    badge: {
        borderRadius: 20,
        paddingHorizontal: scale(10),
        paddingVertical: scale(5),
        marginVertical: 8,
    },
    badgeText: {
        fontSize: moderateScale(12),
        fontWeight: "600",
        color: colors.primary[700] || "#4c1d95",
    },

    cardDesc: {
        fontSize: moderateScale(13),
        color: "#4b5563",
        textAlign: "center",
    },
    cardDescDisabled: {
        color: "#9ca3af",
    },

    footer: {
        color: "#6b7280",
        fontSize: moderateScale(12),
        textAlign: "center",
        marginTop: "auto",
        marginBottom: scale(32),
    },

    fab: {
        position: "absolute",
        bottom: scale(28),
        right: scale(20),
        width: scale(56),
        height: scale(56),
        borderRadius: scale(28),
        backgroundColor: colors.primary[700] || "#6d28d9",
        justifyContent: "center",
        alignItems: "center",
        shadowColor: colors.primary[700] || "#6d28d9",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 8,
    },
});

export const cs = StyleSheet.create({
    // ── Header ──────────────────────────────────────────────
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: 8,
        paddingBottom: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: colors.slate[100],
        backgroundColor: colors.white,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    avatarWrap: {
        position: 'relative',
    },
    avatarImg: {
        width: 28,
        height: 28,
        borderRadius: 21,
        backgroundColor: colors.primary[50],
        borderWidth: 2,
        borderColor: colors.primary[200],
    },
    onlineDot: {
        position: 'absolute',
        bottom: 1,
        right: 1,
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: colors.emerald[500],
        borderWidth: 2,
        borderColor: colors.white,
    },
    headerTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: colors.slate[800],
    },
    headerSub: {
        fontSize: 11,
        color: colors.emerald[600],
        fontWeight: '500',
    },
    closeBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: colors.slate[100],
        alignItems: 'center',
        justifyContent: 'center',
    },
    // ── Empty state ───────────────────────────────────────────
    emptyState: {
        flexGrow: 1,
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 32,
        paddingBottom: 20,
    },
    emptyIconWrap: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: colors.primary[50],
        borderWidth: 2,
        borderColor: colors.primary[100],
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
    },
    emptyTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: colors.slate[800],
        textAlign: 'center',
        marginBottom: 8,
    },
    emptySub: {
        fontSize: 13,
        color: colors.slate[500],
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: 28,
        maxWidth: 300,
    },
    // ── Suggestion grid ───────────────────────────────────────
    sugGrid: {
        width: '100%',
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        justifyContent: 'center',
    },
    sugCard: {
        flexBasis: '47%',
        backgroundColor: colors.primary[50],
        borderRadius: 16,
        borderWidth: 1,
        borderColor: colors.primary[100],
        paddingVertical: 14,
        paddingHorizontal: 14,
        gap: 8,
        shadowColor: colors.primary[900],
        shadowOpacity: 0.04,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
        elevation: 1,
    },
    sugIconCircle: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: colors.primary[100],
        alignItems: 'center',
        justifyContent: 'center',
    },
    sugText: {
        fontSize: 12,
        fontWeight: '600',
        color: colors.slate[700],
        lineHeight: 16,
    },
    // ── Message list ──────────────────────────────────────────
    msgList: {
        paddingHorizontal: 14,
        paddingTop: 14,
        paddingBottom: 8,
        gap: 10,
    },
    bubbleRow: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        gap: 8,
    },
    bubbleRowUser: {
        flexDirection: 'row-reverse',
    },
    botAvatar: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: colors.primary[50],
        borderWidth: 1.5,
        borderColor: colors.primary[200],
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    bubble: {
        borderRadius: 18,
        paddingVertical: 10,
        paddingHorizontal: 14,
        maxWidth: '100%',
    },
    bubbleBot: {
        backgroundColor: colors.slate[100],
        borderBottomLeftRadius: 4,
    },
    bubbleUser: {
        backgroundColor: colors.primary[600],
        borderBottomRightRadius: 4,
    },
    bubbleTxt: {
        fontSize: 14,
        color: colors.slate[800],
        lineHeight: 20,
    },
    ts: {
        fontSize: 10,
        color: colors.slate[400],
        marginTop: 2,
        marginHorizontal: 4,
    },
    // ── Attachment chip (in bubble) ───────────────────────────
    attachChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        borderRadius: 10,
        backgroundColor: colors.primary[50],
        borderWidth: 1,
        borderColor: colors.primary[100],
        paddingVertical: 5,
        paddingHorizontal: 9,
        maxWidth: 220,
        alignSelf: 'flex-start',
    },
    attachChipUser: {
        backgroundColor: colors.primary[700],
        borderColor: colors.primary[500],
        alignSelf: 'flex-end',
    },
    attachChipText: {
        fontSize: 11,
        color: colors.primary[700],
        fontWeight: '500',
        flexShrink: 1,
    },
    // ── Typing dots ───────────────────────────────────────────
    typingDot: {
        width: 7,
        height: 7,
        borderRadius: 3.5,
        backgroundColor: colors.slate[400],
    },
    // ── Quick-reply chip bar ──────────────────────────────────
    chipsBar: {
        // height: 28,
        // flexShrink: 0,
        height: 50,
        maxHeight: 70,
        paddingVertical: 4,
        borderTopWidth: 1,
        borderTopColor: colors.slate[100],
        backgroundColor: colors.slate[50],
    },
    chip: {
        alignSelf: 'center',
        paddingHorizontal: 14,
        paddingVertical: 7,
        borderRadius: 18,
        backgroundColor: colors.primary[50],
        borderWidth: 1,
        borderColor: colors.primary[200],
    },
    chipText: {
        fontSize: 12,
        fontWeight: '600',
        color: colors.primary[700],
        lineHeight: 16,
        includeFontPadding: false,
    },
    // ── Pending attachments bar ───────────────────────────────
    pendingBar: {
        maxHeight: 40,
        backgroundColor: colors.slate[50],
        borderTopWidth: 1,
        borderTopColor: colors.slate[100],
    },
    pendingChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        backgroundColor: colors.primary[50],
        borderWidth: 1,
        borderColor: colors.primary[200],
        borderRadius: 10,
        paddingVertical: 4,
        paddingHorizontal: 8,
        maxWidth: 160,
    },
    pendingChipText: {
        fontSize: 11,
        color: colors.primary[700],
        fontWeight: '500',
        flexShrink: 1,
    },
    // ── Input bar ─────────────────────────────────────────────
    inputBar: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        paddingHorizontal: 12,
        paddingVertical: 10,
        gap: 8,
        borderTopWidth: 1,
        borderTopColor: colors.slate[100],
        backgroundColor: colors.white,
        marginBottom: 10
    },
    inputAction: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: colors.primary[50],
        borderWidth: 1,
        borderColor: colors.primary[100],
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    textInput: {
        flex: 1,
        minHeight: scale(36),
        maxHeight: scale(120),
        backgroundColor: colors.slate[50],
        borderWidth: 1,
        borderColor: colors.slate[200],
        borderRadius: scale(18),
        paddingHorizontal: scale(14),
        paddingTop: scale(8),
        paddingBottom: scale(8),
        fontSize: scale(14),
        color: colors.slate[800],
        lineHeight: scale(20),
    },
    sendBtn: {
        width: scale(36),
        height: scale(36),
        borderRadius: scale(18),
        backgroundColor: colors.slate[200],
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    sendBtnActive: {
        backgroundColor: colors.primary[600],
    },
});

// ================= STYLES =================
export const l_styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    backgroundImage: {
        opacity: 0.45,
        resizeMode: 'cover',
    },
    gradient: {
        flex: 1,
        paddingHorizontal: scale(20),
    },
    scrollContent: {
        alignItems: 'center',
        paddingTop: scale(40),
        paddingHorizontal: scale(16),
        paddingBottom: scale(40),
    },
    scrollWrapper: {
        width: '100%',
    },
    logo: { width: scale(200), height: scale(110), marginBottom: scale(16) },
    title: {
        fontSize: moderateScale(28),
        fontWeight: "800",
        textAlign: "center",
        color: colors.white || "#6d28d9",
        lineHeight: scale(34),
        marginBottom: scale(8),
        letterSpacing: scale(1),
    },
    attentionMessage: {
        fontSize: moderateScale(14),
        fontWeight: "600",
        color: colors.secondary[400] || "#f97316",
        textAlign: "center",
        marginBottom: scale(6),
        lineHeight: scale(20),
    },
    grid: {
        width: '100%',
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        columnGap: scale(12),
        rowGap: scale(16),
        marginTop: scale(16),
    },
    fab: {
        position: "absolute",
        bottom: scale(20),
        right: scale(20),
        width: scale(48),
        height: scale(48),
        borderRadius: scale(24),
        backgroundColor: colors.primary[700] || "#6d28d9",
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#000",
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 5,
    },
    card: {
        flexBasis: '48%',
        maxWidth: scale(320),
        minWidth: scale(140),
        backgroundColor: 'rgba(255,255,255,0.92)',
        borderRadius: scale(22),
        paddingVertical: scale(18),
        paddingHorizontal: scale(14),
        alignItems: 'center',
        shadowColor: '#2d1b4a',
        shadowOpacity: 0.12,
        shadowRadius: scale(14),
        shadowOffset: { width: 0, height: scale(6) },
        elevation: scale(5),
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.4)',
    },
    cardDisabled: { opacity: 0.6 },
    iconWrapper: {
        width: scale(44),
        height: scale(44),
        borderRadius: scale(22),
        alignItems: "center",
        justifyContent: "center",
        marginBottom: scale(8),
    },
    cardTitle: {
        fontSize: moderateScale(14),
        fontWeight: "700",
        marginBottom: scale(2),
        textAlign: "center",
        color: "#111827",
    },
    cardTitleDisabled: { color: "#9ca3af" },
    cardDesc: {
        fontSize: moderateScale(12),
        textAlign: 'center',
        color: '#6b7280',
        marginBottom: scale(8),
        lineHeight: scale(16),
    },
    cardDescDisabled: { color: "#9ca3af" },
    badge: { paddingHorizontal: scale(10), paddingVertical: scale(4), borderRadius: scale(10) },
    badgeText: { fontSize: moderateScale(10), fontWeight: '600' },
    footerContainer: { paddingVertical: scale(16), alignItems: "center" },
    footer: { fontSize: moderateScale(12), color: colors.gray[100], textAlign: "center", marginTop: -scale(30) },
});