export interface DiscretionaryProjectDetailsApproval {
    id: number;
    projectId: number;
    projectTypeId: number;
    applicationStatusId: number;
    submittedBy: string | null;
    submissionDte: string;
    currentApprover: string | null;
    contractNumber: string | null;
    reason: string | null;
    approvalStatus: string | null;
    focusAreaId: number;
    subCategoryId: number;
    interventionId: number;
    otherIntervention: string | null;
    focusCritEvalId: number;
    numberContinuing: number;
    numberNew: number;
    costPerLearner: number;
    gecNew: number;
    gecContinuing: number;
    gecCostPerLearner: number;
    gacNew: number;
    gacContinuing: number;
    gacCostPerLearner: number;
    gcNew: number;
    gcContinuing: number;
    gcCostPerLearner: number;
    hdi: number;
    female: number;
    youth: number;
    numberDisabled: number;
    rural: number;
    province: string | null;
    municipality: string | null;
    district: string | null;
    vision2025goal: string | null;
    sqmrAppIndicator: boolean | null;
    leviesUptodate: boolean | null;
    previousWsp: string | null;
    previousParticipation: string | null;
    dateCreated: string;
    userId: string | null;
    usrUpd: string | null;
    dteUpd: string | null;
    comments: string | null;
    companyTypeId: number;
    companyComplianceId: number;
    discLearnerTypeId: number;
    hiStoricalPerfomanceId: number;
    newCompany: boolean | null;
    linkToSsp: string | null;
}

export interface DiscretionaryProjectDetails {
    id: number;
    projectId: number;
    projectTypeId: number;
    focusAreaId: number;
    subCategoryId: number;
    interventionId: number;
    otherIntervention: string | null;
    focusCritEvalId: number;
    numberContinuing: number;
    numberNew: number;
    costPerLearner: number;
    hdi: number;
    female: number;
    youth: number;
    numberDisabled: number;
    rural: number;
    province: string | null;
    municipality: string | null;
    district: string | null;
    dateCreated: string;
    userId: string | null;
}

export interface DiscretionaryProject {
    id: number;
    organisationId: number;
    projectStatusId: number;
    projectStatDte: string;
    projShortNam: string | null;
    projectNam: string | null;
    grantWindowId: number;
    windowParamId: number;
    projectTypeId: number;
    submittedBy: string | null;
    submissionDte: string;
    totInitReq: number;
    totProj: number;
    totReq: number;
    totFund: number;
    totExpend: number;
    totRcvd: number;
    totDisb: number;
    totGrant: number;
    projMgrId: number | null;
    auditor: string | null;
    auditYyIncl: string | null;
    poAppr: boolean | null;
    poApprDte: string | null;
    poApprNote: string | null;
    finAppr: boolean | null;
    finApprDte: string | null;
    finApprNote: string | null;
    reference: string | null;
    fileLoctn: string | null;
    photoLoctn: string | null;
    captureDte: string;
    nextLogNum: number;
    archiveYn: boolean | null;
    archSetDte: string | null;
    appRef: string | null;
    crPath: string | null;
    gisLong: number | null;
    gisLat: number | null;
    dteUpd: string | null;
    usrUpd: string | null;
    dteCreated: string;
    totOwnCntrb: number;
    totAddFund: number;
    rsaId: number | null;
    rsaAssignedBy: string | null;
    rsaAssignDate: string | null;
    regManagerId: number | null;
    userId: string | null;
    dateCreated: string;
}